### ISSUE TITLE
network connection issues

### ISSUE THREAD

**Issue by u4gy** [bedrock-tool/bedrocktool#105]
![image](https://github.com/bedrock-tool/bedrocktool/assets/113064988/7926f2fd-0668-4758-b4fd-f6ad13f8d597)

**Comment by olebeck** [comment]
this is the same issue as #97
since its a networking issue and failing to do an http request im not sure how much i can do, i havent seen this issue pop up for anything but your specific setup.
this is likely to be some outside security system interfering

**Comment by u4gy** [comment]
@olebeck can I change my token.json to another account as it may be some changes i made to the current account i am using in the token.json

**Comment by u4gy** [comment]
@olebeck I get the same error when I disable my VPN, Ive reinstalled it and everything

How can I change the account it uses like in the token.json

**Comment by olebeck** [comment]
you rename or delete the token.json and you can sign in with a different account

**Comment by u4gy** [comment]
@olebeck I set up duel boot on my pc and tried it on win10 now it wont connect on the listing but there is no error in logs

**Comment by olebeck** [comment]
found root cause and fixed
