### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by iKilres** [bedrock-tool/bedrocktool#106]
when you enter "listening" screen in the gui, when you join your server, the loading screen shows "loading resource packs" then later says a connection error occured. ive tried to see whats the problem but it isnt working.(url)
![image](https://github.com/bedrock-tool/bedrocktool/assets/145150417/5612631a-d8dd-410f-a6ba-234bb49116f0)

**Comment by olebeck** [comment]
what version is this on

**Comment by iKilres** [comment]
this is on 1.20.15

> what version is this on
