### ISSUE TITLE
-preload=false flag crashes 

### ISSUE THREAD

**Issue by jqms** [bedrock-tool/bedrocktool#11]
```-preload=false skins-proxy``` crashes it without warning

**Comment by olebeck** [comment]
closing the issue for now since i cant reproduce the error, feel free to reopen if you still have the issue and can help with reproducing the error so it can be fixed!

**Comment by jqms** [comment]
it crashes immediately after pressing enter when adding the flag
eg
-preload=false worlds

**Comment by olebeck** [comment]
how exactly are you running the program

**Comment by jqms** [comment]
> 

double clicking it and opening it

**Comment by olebeck** [comment]
To use extra cli flags you need to run it through a console, the interactive input only supports selecting the subcommand

**Comment by olebeck** [comment]
this should now work with the new usability change

**Comment by jqms** [comment]
alright neat
