### ISSUE TITLE
world archiving | cubecraft | corruption

### ISSUE THREAD

**Issue by BedrockToolLoverAchieved** [bedrock-tool/bedrocktool#112]
Downloading worlds from the CubeCraft server is broken. Now you can load into the server and everything, but the problem occurs when you import the world into the game and load into it to find massive amounts of corrupt chunks and nothing of the map that you thought it was going to download.

1, type in the worlds command.
2. enter in the server mco.cubecraft.net
3. open up minecraft.
4. load into into you localhost server.
5. download something.
6. save what you have downloaded.
7. import the word into the game.
8. load into the world.
9.  see the bug.

Now what is supposed to happen is that when you save the world and import it into the game, you are meant to see the map with the items you had and the position you were at when you finished downloading it.

"Connecting to mco.cubecraft.net:19132"
"received remote pack infos"
"waiting for remote stack"
"received remote resourcepack stack, starting game"
"Using Custom Blocks"
"couldnt determine game version, assuming > 1.18"
"Connected to server."

![Minecraft 25_09_2023 11_48_27 AM](https://github.com/bedrock-tool/bedrocktool/assets/145944744/4891efa9-a112-48f9-95ab-af3250343890)

**Comment by olebeck** [comment]
this was due to block states being changed in 1.20.30, forgot to update the nbt file.
this works now however there is still another issue specific to cubecraft, where a single layer of sand or water is missing
