### ISSUE TITLE
Behavior download missing

### ISSUE THREAD

**Issue by Namvn2006** [bedrock-tool/bedrocktool#115]
**Describe the bug**
A clear and concise description of what the bug is,
and optionally what server it occurs on.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Version [e.g. 1.28.0-36]
 - Minecraft Version [e.g. 1.19.73]
![play cubecraft net 02_10_2023 20_48_38](https://github.com/bedrock-tool/bedrocktool/assets/146732360/47470a9c-d607-4834-be18-84ec273a19d2)

**Additional context**

**attach packets.log.g
![manifest json - Notepad 02_10_2023 20_48_25](https://github.com/bedrock-tool/bedrocktool/assets/146732360/fe5af2b5-5802-4843-987f-cd8f59645471)
pg (not always necessary)**
this file can be helpful for debugging without having to connect to the server.
it can be created by running with -extra-debug [e.g. bedrocktool.exe -extra-debug worlds -address play.mojang.com ]
be sure to only attach the .gpg file which is not publicly readable.

**Comment by olebeck** [comment]
you didnt fill out any of the text prompts, only sent screenshots. can you please explain what the issue is
