### ISSUE TITLE
pack downloader doesn't decrypt sound or lang files

### ISSUE THREAD

**Issue by eeeeeeeeewastaken** [bedrock-tool/bedrocktool#116]
**Describe the bug**
when you download a pack, sound files and texts files aren't decrypted

**To Reproduce**
1. download a pack from any featured server
2. check files inside
3. try to open sound files (it won't work)
4. same above with the texts folder

**Expected behavior**
the files shouldve been decrypted

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: 10.0.19045.3448
 - Minecraft Version: 1.20.30

**attach packets.log.gpg (not always necessary)**
this file can be helpful for debugging without having to connect to the server.
it can be created by running with -extra-debug [e.g. bedrocktool.exe -extra-debug worlds -address play.mojang.com ]
be sure to only attach the .gpg file which is not publicly readable.

**Comment by olebeck** [comment]
cant reproduce, works fine for me, please be more specific in what you are doing
