### ISSUE TITLE
not logging to galaxite.

### ISSUE THREAD

**Issue by iKilres** [bedrock-tool/bedrocktool#119]
not sure why, but when I go to galaxite the host immediately shuts down, ive attempted to downgrade versions and use early ones too, there doesn't seem to be a difference, may I ask why this is occurring?

it would mention this then close the moment galaxites logo appears in the loading screen:

time="2023-10-23T20:19:37+01:00" level=info msg="Bedrocktool Version 1.32.0-30"
time="2023-10-23T20:19:44+01:00" level=info msg="Listening on [::]:19132"
time="2023-10-23T20:19:44+01:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2023-10-23T20:19:48+01:00" level=info msg="Connecting to play.galaxite.net:19132"
time="2023-10-23T20:19:50+01:00" level=debug msg="received remote pack infos"
time="2023-10-23T20:19:50+01:00" level=debug msg="waiting for remote stack"
time="2023-10-23T20:19:50+01:00" level=debug msg="received remote resourcepack stack, starting game"
time="2023-10-23T20:19:50+01:00" level=info msg="Using Custom Blocks"

**Comment by olebeck** [comment]
galaxite has a server bug that causes the StartGame packet to be sent twice, which means custom blocks are registered twice, fixed in newest version. any but the first StartGame is ignored now
