### ISSUE TITLE
Wrong name of game npcs in hive

### ISSUE THREAD

**Issue by ChickenCMB** [bedrock-tool/bedrocktool#123]
All NPCs are named Just Build

![Screenshot_1](https://github.com/bedrock-tool/bedrocktool/assets/145242044/95fd4911-c5d0-46ac-9b85-6a30d8b6a022)

**Comment by Sinu03** [comment]
How did you join the hive server with bedrocktool?

**Comment by olebeck** [comment]
this bug has been fixed now it was due to an update on their side breaking an assumption i made about the protocol
