### ISSUE TITLE
Change protocol/Minecraft Versions

### ISSUE THREAD

**Issue by Lxpqx** [bedrock-tool/bedrocktool#131]
**Is your feature request related to a problem? Please describe.**
Recently I was trying to use the word downloader on a server which did not use the same version as the software. I was trying to find a way/setting that would let me do so. But I was not able to find anything.

**Describe the solution you'd like**
As a solution I would like to implement a feature that lets u change the protocol or version of the tool to be able to join any server

**Describe alternatives you've considered**
It could include a box to wright the protocol u would like.

**Additional context**
For additional context here is the error I get :
023/12/21 16:12:55 error:  connected with an incompatible protocol: expected protocol = 557, client protocol = 630

**Comment by olebeck** [comment]
its fairly high maintainance to support multiple protocol versions, however program has been updated to support latest (630) protocol version now so this should work now
