### ISSUE TITLE
Error when downloading map

### ISSUE THREAD

**Issue by ImFeyr** [bedrock-tool/bedrocktool#133]
**Describe the bug**
Ex: When I enter TheHive it normally downloads the world, when I enter The Bridge and start the game, Bedrock Tools simply closes.

**Screenshots**
Bedrock Tools close.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Minecraft Version [Latest]

**Additional context**
I can download the first map (when it enters the server) but when the minigames start where the player is teleported, Bedrock Tools closes

**Comment by olebeck** [comment]
should be fixed now, reopen if not
