### ISSUE TITLE
interface conversion error

### ISSUE THREAD

**Issue by Zwuiix-cmd** [bedrock-tool/bedrocktool#142]
**Describe the bug**
time="2024-01-24T02:11:40+01:00" level=error msg="write packet minecraft [::]:19132->127.0.0.1:49672: use of closed network connection"
time="2024-01-24T02:11:40+01:00" level=info msg="Saved: worlds/127.0.0.1/world-5.mcworld"
time="2024-01-24T02:11:40+01:00" level=error msg="interface conversion: interface {} is nil, not string"

**To Reproduce**
1. Go to 'mcpe.plutonium.best:19132'

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1°
 - Minecraft Version 1.20.50

**Comment by olebeck** [comment]
should be fixed now
