### ISSUE TITLE
It doesn't download worlds

### ISSUE THREAD

**Issue by NJMD13** [bedrock-tool/bedrocktool#148]
**Describe the bug**
When trying to download a world either from a server like Cubecraft or one created with BDS hosted on my own network from another PC, no chunks are downloaded and in the bedrocktool console, I get this message: time="2024-02-11T03:24:08-06:00" level=error msg="bug check: subchunk received before chunk"

**To Reproduce**
1. Open Bedrocktool
2. "I set the IP of the server I want to download the world from
3. In the options to select, I only leave the 'void' option checked (It doesn't matter which option I activate or deactivate).
4. I press the Start button.
5. I connect using the local IP address.
6. And upon connecting, it doesn't download anything and gives me the mentioned error from the console.

**Expected behavior**
I expected it to download the world as it does on the NetherGames server.

**Screenshots**
![image](https://github.com/bedrock-tool/bedrocktool/assets/57160583/8689aaad-d1c7-4c2b-8edd-97221a23f27d)

**Desktop:**
 - OS: Windows 10
 - Version 1.35.0-1-gui
 - Minecraft Version 1.20.60

**attach packets.log.gpg (not always necessary)**
[bedrocktool.log](https://github.com/bedrock-tool/bedrocktool/files/14231890/bedrocktool.log)

**Comment by HiveLanky** [comment]
same thing here buddy.

**Comment by olebeck** [comment]
cubecraft works fine in latest, so should be fixed

**Comment by NJMD13** [comment]
> cubecraft works fine in latest, so should be fixed

In the new version, it doesn't let me connect to any server. I use version 1.21.1 of Minecraft and version "1.38.0-4" of bedrocktool and it doesn't let me.

I already opened port 19132, gave permissions through the Windows firewall, used my public IP, local IP as localhost, and 127.0.0.1, and it doesn't work.

I thought it was on my end, so I downloaded Minecraft 1.20.81 and version "1.37.0-3" of bedrocktool, and everything works correctly.

It doesn't show any error data in the console, the connection just doesn't appear.

**Comment by olebeck** [comment]
I changed it to listen on localhost by default, can you try it with listen set to 0.0.0.0:19132,
if that works I will revert it back to that as default.

**Comment by NJMD13** [comment]
Perfect, if it works for me with 0.0.0.0:19132

**Comment by olebeck** [comment]
changed the default back to 0.0.0.0:19132, saw this issue happen for someone else so this seems like the better default
