### ISSUE TITLE
OS Windows 10

### ISSUE THREAD

**Issue by Akill8412** [bedrock-tool/bedrocktool#153]
**Describe the bug**
A clear and concise description of what the bug is,
and optionally what server it occurs on.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Version [e.g. 1.28.0-36]
 - Minecraft Version [e.g. 1.19.73]

**Additional context**

**attach packets.log.gpg (not always necessary)**
this file can be helpful for debugging without having to connect to the server.
it can be created by running with -extra-debug [e.g. bedrocktool.exe -extra-debug worlds -address play.mojang.com ]
be sure to only attach the .gpg file which is not publicly readable.

**Comment by olebeck** [comment]
you didnt fill out any of the sections in the template, please give more details
