### ISSUE TITLE
Unable to connect to world: Localhost & 127.0.0.1 Issue

### ISSUE THREAD

**Issue by whitejaws** [bedrock-tool/bedrocktool#156]
**Describe the bug**
When joining 127.0.0.1 with Bedrocktool listening, the server appears inactive and unable to be joined.

**To Reproduce**
1. Go to bedrocktool-windows-amd64-1.35.0-1-gui
3. Click on servers and only put server ip as ca.hivebedrock.network
4. Open Minecraft Bedrock v1.20.62 
5. Make server with ip: 127.0.0.1 with port: 19132 
6. See error number 1: server still says "Locating Server" and is inactive
7. Open server
8. See error number 2: "Unable to connect to world."

**Expected behavior**
Able to join Bedrock servers and download worlds.

**Screenshots & additional context**
In the first & second images, these screenshots showcase the ip and ports I've used and haven't work out - according to https://doc.pmmp.io/en/rtfd/faq/connecting/win10localhostcantconnect.html#don-t-use-localhost-for-server-address

In the third image, "[: :]" Seems like another ip to be used, but I dunno how to spell it out in Bedrock and have it save as an actual server.

![image](https://github.com/bedrock-tool/bedrocktool/assets/161795894/022308bb-a381-48db-b77c-3ea4a11545c7)
![image](https://github.com/bedrock-tool/bedrocktool/assets/161795894/9eae1b38-4993-487f-9a2c-3af1c3e16477)
![image](https://github.com/bedrock-tool/bedrocktool/assets/161795894/60cd708c-b48a-4b2e-a945-73610dedddc7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: bedrocktool-windows-amd64-1.35.0-1-gui
 - Minecraft Version: v1.20.62

**attach packets.log.gpg (not always necessary)**
N/A.

**Comment by zrannx** [comment]
Follow this:
https://doc.pmmp.io/en/rtfd/faq/connecting/win10localhostcantconnect.html
