### ISSUE TITLE
terracota glitch

### ISSUE THREAD

**Issue by zrannx** [bedrock-tool/bedrocktool#158]
**Describe the bug**
When downloading a world , every structure and terrain turns into pure terracota blocks

**To Reproduce**
1. join a random server with the worlds option
2. load chunks (the map in hand shows just a terracota plain)
3. leave and save the world
4. join the world and everything will be turned into terracota cubes 

**Screenshots**
just imgine a flat world made of terracota filled with random cubes

**Desktop (please complete the following information):**
 - OS: windows
 - Version: latest
 - Minecraft Version: latest
 
 Edit:
 The glitch only occurs on realms/bds and some external servers.

**Comment by fruit-jazz** [comment]
I have the same problem, I understand it's because of bds

**Comment by HiveLanky** [comment]
Same Bug here.

**Comment by HiveLanky** [comment]
It lets me download servers perfectly but when I try downloading realms thats when I get this bug.

**Comment by afarhansib** [comment]
same bug, works with geyser proxy (java server). doesn't work with realm/bds

**Comment by PeawGitHub** [comment]
Any fixs for this? I'm having the same issue with a server. Chunks I load are just filled with a custom block the server has, so the world is just out of large brown cubes.

**Comment by olebeck** [comment]
should now work fine, rid hash sorting is corrected
