### ISSUE TITLE
Add a way to add a custom port

### ISSUE THREAD

**Issue by HiveLanky** [bedrock-tool/bedrocktool#159]
Add a way to add a custom port

**Comment by zrannx** [comment]
there is already

**Comment by zrannx** [comment]
(server ip):(custom port)
example: play.someserver.net:83732

**Comment by HiveLanky** [comment]
zrannx able to help me with stuff?

**Comment by olebeck** [comment]
you can do both -address serveryouwanttoconnectto:port and -listen 127.0.0.1:portyouwanttheproxyon
this now lets you set custom port for both
