### ISSUE TITLE
Needs Update To 1.20.71

### ISSUE THREAD

**Issue by ikonikisop** [bedrock-tool/bedrocktool#161]
How To See This Bug.
1. Go to 'Worlds'
2. Enter World Address
3. Click on 'Start'
Then When Trying To Connect To 127.0.0.1 It Says:
![image](https://github.com/bedrock-tool/bedrocktool/assets/129855365/80f6e62e-472e-493e-93ef-098e89a0e700)

Please Fix This, Thanks.

**Comment by HiveLanky** [comment]
I hope this gets fixed soon
