### ISSUE TITLE
Save chunks

### ISSUE THREAD

**Issue by needlelenok** [bedrock-tool/bedrocktool#164]
Terracotta is saved instead of the necessary blocks

**Screenshots**
![image](https://github.com/bedrock-tool/bedrocktool/assets/122255485/05e2c801-9589-42e9-a12e-def3fa8ecfaa)
![image](https://github.com/bedrock-tool/bedrocktool/assets/122255485/6fcefc64-4b00-431d-b62d-4272aec3cdd4)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 11]
 - Version [e.g. r1.35.0]
 - Minecraft Version [e.g. 1.19.62]

**Comment by zrannx** [comment]
i already made a post explaining this , feel free to check it out
https://github.com/bedrock-tool/bedrocktool/issues/158#issue-2177792946

**Comment by olebeck** [comment]
should now work fine, rid hash sorting is corrected
