### ISSUE TITLE
World Import Failed.

### ISSUE THREAD

**Issue by ikonikisop** [bedrock-tool/bedrocktool#165]
When downloading a world everything goes well, except when importing the world it says "World Import Failed" and the log looks fine.

**To Reproduce**
1. Open the World.mcworld
2. Then when it says importing it says "World Import Failed"

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [10.0.22631 Build 22631]
 - Minecraft Version [1.20.71]

[bedrocktool.log](https://github.com/bedrock-tool/bedrocktool/files/14609347/bedrocktool.log)

**Comment by ikonikisop** [comment]
I wonder if i have to do it manually maybe?

**Comment by ikonikisop** [comment]
That was the issue!

**Comment by olebeck** [comment]
this is an issue with the CTF Assets resource pack, specifically a single png it seems to be a issue with minecraft
easiest fix is deleting the CTF Assets resourcepacks from the mcworld
