### ISSUE TITLE
Can't Connect To World.

### ISSUE THREAD

**Issue by ikonikisop** [bedrock-tool/bedrocktool#166]
When Trying To Load Into "join.wildwoodsmp.com" its an infinite loading resource packs screen. (I have Disabled UWP loopback restrictions)

1. Host the server on Bedrocktool.
2. Try to join 127.0.0.1 or ::1 or localhost
3. Infinte loading screen and in log "[::]"

Desktop
 - OS: [Windows 11]
 - Version [0.0.22631 Build 22631]
 - Minecraft Version [1.20.71]

**Comment by zrannx** [comment]
Follow this guide:
https://doc.pmmp.io/en/rtfd/faq/connecting/win10localhostcantconnect.html

**Comment by zrannx** [comment]
try more times , it worked for me

**Comment by ikonikisop** [comment]
> try more times , it worked for me

What Version?
