### ISSUE TITLE
I can't run it (MC 1.20.71, bedrocktool 1.36.0-3)

### ISSUE THREAD

**Issue by PeawGitHub** [bedrock-tool/bedrocktool#167]
I can't run the program, my pc is Windows 11 and MC version is 1.20.71

The program immediately closes itself when I run it. I attached the bedrocktool.log file it creates.

[bedrocktool.log](https://github.com/bedrock-tool/bedrocktool/files/14616370/bedrocktool.log)

**Comment by olebeck** [comment]
fixed in latest version
