### ISSUE TITLE
Downloaded world is "corrupted"

### ISSUE THREAD

**Issue by PeawGitHub** [bedrock-tool/bedrocktool#171]
When I try to download any world of play.craftersmc.net, all the world has is just a custom block from the server. Like the world only has large cubes that is made out of a custom block.
![image](https://github.com/bedrock-tool/bedrocktool/assets/118385226/d8835a5f-4994-4099-9f50-73e76415fbea)
(This is not brown concrete, it's a custom block from the server that looks like a brown concrete.)

I'm using Windows 11 and my Minecraft version is 1.20.71. bedrocktool version is 1.36.0-4

**Comment by HiveLanky** [comment]
Has been known for a while now. No one knows how to fix it

**Comment by olebeck** [comment]
this should be fixed with r1.38.0
