### ISSUE TITLE
Issue: The host is using an older version of Minecraft.

### ISSUE THREAD

**Issue by USBMenus** [bedrock-tool/bedrocktool#172]
**Describe the bug**
When i try to download a world, it will not list the realms, so i have to get the ip address, when i click start it will host it on my machine, but when i join it will say the host is on a different version, and when i try to rejoin it will crash the program

**To Reproduce**
1. start the gui version
2. Go to worlds
3. type in the server/realms address
4. Click start
5. join localhost/127.0.0.1 server
6. get kicked for being on a different version
7. try to join again (program crashes)

**Expected behavior**
I expect it not to crash

**Screenshots**
![Version Error](https://github.com/bedrock-tool/bedrocktool/assets/69381115/973a88f6-cb8b-4397-9754-c60a67a9b7c8)

**Desktop**
 - OS: Windows 10
 - Version 1.36.0-7 (gui)
 - Minecraft Version 1.20.80

**Log**
[bedrocktool.log](https://github.com/bedrock-tool/bedrocktool/files/15126284/bedrocktool.log)

**Comment by HiveLanky** [comment]
it wont work at all in the new version
