### ISSUE TITLE
World Download Corruption and Crash When Clicking List Realms

### ISSUE THREAD

**Issue by USBMenus** [bedrock-tool/bedrocktool#175]
**Describe the bug**
When i click on the 'list realms' button, it loads for a second and then crashes
if i try to use the ip itll work all the way up to joining the local server, but then itll say 'Server sent broken packet.'

**To Reproduce**
1. Click 'list realms' button(which will crash the tool) or enter the ip
2. connect to the server
3. receive broken packet error after connecting

**Expected behavior**
I expect to be able to download the world and use the tool properly

**Screenshots**
![image](https://github.com/bedrock-tool/bedrocktool/assets/69381115/c58d3591-a778-43b6-abac-12458b10e9ee)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.37.0-2
 - Minecraft Version: 1.20.81

**Additional context**
It will save in 'worlds/{ip}/{world name}' but it will only be a very small chunk of the world, and everything is cyan terracotta, it only shows some items from only my inventory, all other players and data are corrupted
 
this is the log
[bedrocktool.log](https://github.com/bedrock-tool/bedrocktool/files/15371119/bedrocktool.log)

**Comment by olebeck** [comment]
both of these should be fixed now, i tested on custom server with default settings which should be the same as realms
