### ISSUE TITLE
Can't connect to geyser servers

### ISSUE THREAD

**Issue by Agaloth** [bedrock-tool/bedrocktool#178]
**Describe the bug**
time="2024-06-04T17:09:51+02:00" level=info msg="Bedrocktool Version 1.37.0-3"
time="2024-06-04T17:09:55+02:00" level=info msg="Connecting to play.terraemc.net:19132"

And it pretty much gets stuck there (I tried waiting 30 minutes and nothing happened as well)

**To Reproduce**
1. Run a spigot/paper server with Geyser (for bedrock crossplay)
2. Join the server via bedrocktool
3. See error

**Expected behavior**
It should connect and download the pack

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.37.0
 - Minecraft Version 1.20.81

**Additional context**
Geyser might have their own way of connecting players? This is what I've seen on their discord after checking it up:
`Geyser has a cookie handshake, if you're not responding to that, that could be one reason. You need to look at the docs in the wiki, and see what exactly is being sent and received`

**Comment by olebeck** [comment]
go-raknet doesnt implement cookies, however i can add this fairly to the library easily

**Comment by olebeck** [comment]
actually seems like it does do the cookie handshake correctly
