### ISSUE TITLE
what do i do here to download world?

### ISSUE THREAD

**Issue by YoXpertguyZ** [bedrock-tool/bedrocktool#18]
![image](https://user-images.githubusercontent.com/62682645/209414213-b733ad4e-8365-4a20-9532-519d55be049b.png)

**Comment by olebeck** [comment]
You have to open minecraft and connect to localhost server

**Comment by StrafeYourself** [comment]
Bro marry charismas, By the why are you ignoring me my friend did I do something wrong?
