### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by bzxtm** [bedrock-tool/bedrocktool#181]
**Describe the bug**
after i connect to the server nothing loads as if an standing in the void for a couple of seconds then i get kicked out ans see a connection lost error code and i get a fatal panic message on the bedrocktool

**To Reproduce**
1. start bedrock tool 
2. Click on words
3. enter ip address and join the server

**Expected behavior**

**Screenshots**
![image](https://github.com/bedrock-tool/bedrocktool/assets/172304252/da9b8963-09f8-4407-b33a-2c11321bc226)
![image](https://github.com/bedrock-tool/bedrocktool/assets/172304252/49dddc8e-6a30-42e8-971d-0c71d56fc286)

**Desktop (please complete the following information):**
 - OS:  windows 10
 - Version [1.37.0-3]
 - Minecraft Version [ 1.20.80]

**Comment by olebeck** [comment]
should be fixed
