### ISSUE TITLE
Crashes when I click List Realms

### ISSUE THREAD

**Issue by TheToasttMan** [bedrock-tool/bedrocktool#188]
When I open the tool, with admin or not. I navigate over to the worlds tab and click "list realms." It will act like its trying to load and then close/crash the application. This happens regardless if minecraft is open or not.

 - OS: Windows 10
 - Version 19045.4412
 - Minecraft Version Latest

Here is what I assume to be the log file:

time="2024-06-24T10:42:38-04:00" level=info msg="Bedrocktool Version 1.38.0-7"
panic: assignment to entry in nil map

goroutine 13 [running]:
github.com/bedrock-tool/bedrocktool/ui/gui/popups.(*RealmsList).Load(0xc0003ac808)
	/home/runner/work/bedrocktool/bedrocktool/ui/gui/popups/realmsinput.go:50 +0x12a
created by github.com/bedrock-tool/bedrocktool/ui/gui/popups.(*RealmsList).Layout.func1.1 in goroutine 1
	/home/runner/work/bedrocktool/bedrocktool/ui/gui/popups/realmsinput.go:94 +0xc5

**Comment by olebeck** [comment]
thanks for adding the crash log, should be fixed now

**Comment by TheToasttMan** [comment]
thanks! if its easier I can make a new ticket but currently its stuck at the "listening" screen.
This is with the bedrock client open and I even joined the realm. I suppose this *could* be something on my end but im not sure what would cause this.
Here's the log file again:

time="2024-06-24T11:06:13-04:00" level=info msg="Bedrocktool Version 1.38.0-8"
time="2024-06-24T11:07:11-04:00" level=info msg="Listening on [::]:19132"
time="2024-06-24T11:07:11-04:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"

**Comment by TheToasttMan** [comment]
fixed it. but cant figure out if its actually downloading anything
