### ISSUE TITLE
World DL doesn't work. 

### ISSUE THREAD

**Issue by dmywmy** [bedrock-tool/bedrocktool#189]
As soon as connecting to local server, Minecraft gives an error "Disconnected from Server". 
Bedrocktool gets stuck on "Connecting to Server" and when reconnecting to local server, Bedrocktool crashes.

![image](https://github.com/bedrock-tool/bedrocktool/assets/173832448/126cf8f7-c0ec-4199-a8a6-d2c6ddac55ee)

LOG:
time="2024-06-26T03:21:19+10:00" level=info msg="Bedrocktool Version 1.38.0-8"
time="2024-06-26T03:21:29+10:00" level=info msg="Listening on [::]:19132"
time="2024-06-26T03:21:29+10:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-06-26T03:22:00+10:00" level=info msg="Connecting to SERVER (I removed IP for privacy reasons)"
2024/06/26 03:22:00 listener conn: handle *packet.Login: parse login request: validate client data: PlayFabID must be hex string, but got 268643f99aa872f
panic: close of closed channel

goroutine 126 [running]:
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).connectClient.func3(0xc001310008)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/conn.go:123 +0x139
github.com/sandertv/gophertunnel/minecraft.(*Listener).handleConn(0xc000efcc30, 0xc001310008)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/listener.go:286 +0x96
created by github.com/sandertv/gophertunnel/minecraft.(*Listener).createConn in goroutine 33
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/listener.go:261 +0x3ed

Help me get this working please. My discord is aka.dom if you want to contact me directly.

**Comment by olebeck** [comment]
*packet.Login: parse login request: validate client data: PlayFabID must be hex string, but got 268643f99aa872f
this is the issue, problem is that it starts with a zero which is omitted. should be easy to fix
