### ISSUE TITLE
ERROR[0147] use of closed network connection

### ISSUE THREAD

**Issue by wadudi82** [bedrock-tool/bedrocktool#197]
ERRO[0147] use of closed network connection              part=ResourcePacks
ERRO[0147] dial minecraft 192.168.178.103:51166->104.208.152.151:30238: use of closed network connection

This error happens when i try to download large ResourcePacks (in this case its around 170mb) or multiple of them on Realms 

 - OS: [Windows]
 - Version [1.38.0]
 - Minecraft Version [1.21.1].
 
![image](https://github.com/bedrock-tool/bedrocktool/assets/100869678/90484dc5-3484-4967-8cd4-24c432a273fb)
![image](https://github.com/bedrock-tool/bedrocktool/assets/100869678/0747acf8-5497-430a-a9f0-997ec4f3765a)

**Comment by olebeck** [comment]
this may be caused by the multiple duplicate resourcepacks, new version should be more robust at dealing with that. please try again

**Comment by wadudi82** [comment]
Can u add support for the new Minecraft protocol

**Comment by olebeck** [comment]
update done

**Comment by wadudi82** [comment]
Thanks, is it possible to directly dump the keys?, when I do "only-keys" the pack is still downloaded, I put a fake zip file on the packcache and when I start "packs" with the option only-keys I see that the download process is skipped and it dumps the key so i assume it can presumably be done

**Comment by olebeck** [comment]
yes, added in newest
