### ISSUE TITLE
Custom Blocks Don't Save

### ISSUE THREAD

**Issue by StrafeYourself** [bedrock-tool/bedrocktool#20]
Hey olebeck,
StrafeYourself here, So I have had some minor issues with the bedrock tool, So I am trying to archive the hive charismas hub however, however since the hive added custom blocks in the hub bedrock tool does not know how to save it turning all the chunks containing a custom block into air. Anyway, here is the error I really do hope you can fix it before the charismas hive hub disappears. Since it is a yearly event sought of thing and it would cause me great pain just to pain until next year.

time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_wide_gift_box_yellow{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_snowy_stone_transition{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_snowy_stone_transition{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_dark_metal_truss_pane{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_blue{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_green{map[custom:facing_direction:3]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_white{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_blue{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_green{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_dark_metal_truss_pane{map[custom:facing_direction:3]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_wide_gift_box_red{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_green{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_green{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_red{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_green{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_wide_gift_box_yellow{map[custom:facing_direction:3]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_red{map[custom:facing_direction:3]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_spruce_large_planks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_red_painted_toy_train{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_toy_bear{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_pink_toy_bear{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_red{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_white{map[custom:facing_direction:3]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_wide_gift_box_green{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_white{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_cookies_and_milk{map[custom:facing_direction:1]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_blue{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:07+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_terracotta_bricks{map[]}"
time="2022-12-25T12:32:08+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_white{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:08+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_green{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:08+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_green{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:08+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_white{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:08+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_blue{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:38+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_white{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:39+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_green{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:39+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_gift_box_green{map[custom:facing_direction:2]}"
time="2022-12-25T12:32:44+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_white{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:44+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_blue{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:50+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_white{map[custom:facing_direction:0]}"
time="2022-12-25T12:32:51+10:00" level=error msg="cannot get runtime ID of block state hive:zzub_tall_gift_box_blue{map[custom:facing_direction:0]}"

Remarks StrafeYourself

**Comment by DidntPot** [comment]
the proxy doesn't support custom blocks

**Comment by olebeck** [comment]
added custom block support, it still needs work to generate behavior packs but it saves now
