### ISSUE TITLE
Unable to Connect to other servers with different ports

### ISSUE THREAD

**Issue by HiveLanky** [bedrock-tool/bedrocktool#204]
time="2024-07-27T17:02:10-06:00" level=info msg="Bedrocktool Version 1.39.1-19" part=main
time="2024-07-27T17:03:02-06:00" level=info msg="Listening on [::]:19132"
time="2024-07-27T17:03:02-06:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-07-27T17:03:18-06:00" level=info msg="Connecting to 173.240.154.247:19200"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[36mC\x1b[0m->\x1b[32mS\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x8f, packet.NetworkSettings"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[36mC\x1b[0m->\x1b[32mS\x1b[0m 0x01, packet.Login"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x03, packet.ServerToClientHandshake"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[36mC\x1b[0m->\x1b[32mS\x1b[0m 0x04, packet.ClientToServerHandshake"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x02, packet.PlayStatus"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[36mC\x1b[0m->\x1b[32mS\x1b[0m 0x81, packet.ClientCacheStatus"
time="2024-07-27T17:03:19-06:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x06, packet.ResourcePacksInfo"
panic: read manifest: error decoding manifest JSON: json: cannot unmarshal string into Go struct field Module.modules.version of type [3]int (data: {
    "format_version": 2,
    "header": {
        "name": "§3Asteroid Resources 1.0.0 §b[R]",
        "description": "§bResource pack for Asteroid PvP. Made by Asteroid.",
        "u​u​id​": "1ff1988c-22c8-44ae-b135-ed1c43dd1973",
        "uu​i​d": "9fd2872e-fb50-44ea-a5b3-43136bc3e26a",
        "u​u​i​d​": "a3da64dd-1231-40e5-8861-aef07451b390",
        "u​ui​d​": "e36da9fc-c68f-44cc-8e10-09a5ff89e6ea",
        "u​uid​": "9be0cc4c-9911-43af-ae7f-fd2d7b9cd69d",
        "u​ui​d​": "cca9263f-4ed3-4663-be31-a2bfd6c6fa7f",
        "u​u​id": "c5995e01-eb88-4952-8a95-1dbc910343a0",
        "uu​i​d​": "71344600-061f-4c73-a0ea-50614e5fb3d5",
        "uu​id​": "0be96c5a-d6f8-4380-88be-0a497076c689",
        "u​u​id": "191b92df-7559-48d2-ab44-9e3cc0f83fdf",
        "uu​id​": "b8466fa2-57b8-4e17-8954-004ce0060414",
        "uu​id": "51e20c2b-3382-4ace-9059-a5373171d476",
        "u​ui​d": "8e1447b1-1989-4c86-a1a5-d26dcab55606",
        "u​uid​": "357bcbb0-0bf7-4e24-b0a5-d0a349f3e96a",
        "uu​id​": "6d61b79e-f30f-46e9-bb8c-41b3d2eef10f",
        "uu​id​": "c0bbccca-c8b8-4ccf-8f6d-61f9f9cf5ac2",
        "uu​id​": "341263b2-34de-4e23-a22d-11e619a1e180",
            "version": "1.0.0"
        }
    ],
    "metadata": {
        "authors": [
            "autosteroid"
        ]
    }
})

goroutine 92 [running]:
github.com/sandertv/gophertunnel/minecraft/resource.MustReadPath(...)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/resource/pack.go:113
github.com/bedrock-tool/bedrocktool/utils/proxy.(*packCache).Get(0xc00259f440?, {0xc00259f3e0?, 0xc00259f3e0?}, {0xc0013053d2?, 0xc001801a50?})
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/packcache.go:28 +0xce
github.com/bedrock-tool/bedrocktool/utils/proxy.(*rpHandler).OnResourcePacksInfo.func1({0xc00259f3e0, 0x24}, {0xc0013053d2, 0x5}, {0x2508660, 0x0}, 0x729d2b)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/resourcepacks.go:170 +0x1a3
github.com/bedrock-tool/bedrocktool/utils/proxy.(*rpHandler).OnResourcePacksInfo(0xc000258000, 0xc000b2eae0)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/resourcepacks.go:285 +0x29f
github.com/sandertv/gophertunnel/minecraft.(*Conn).handlePacket(0xc00148c008, {0x154acd0, 0xc000b2eae0})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:713 +0x48f
github.com/sandertv/gophertunnel/minecraft.(*Conn).handleMultiple(0xc00148c008, {0xc0014c6880?, 0xc001305360?, 0xc000f0a900?})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:673 +0x85
github.com/sandertv/gophertunnel/minecraft.(*Conn).handle(0xc00148c008, 0x66?)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:659 +0xb6
github.com/sandertv/gophertunnel/minecraft.(*Conn).receive(0xc00148c008, {0xc00118e2d7?, 0x3fc66c584419e5e8?, 0xc0011f9f40?})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:647 +0x19f
github.com/sandertv/gophertunnel/minecraft.listenConn(0xc00148c008, 0xc000046300, 0xc00126d440, 0xc00126d4a0)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/dial.go:329 +0x1ea
created by github.com/sandertv/gophertunnel/minecraft.Dialer.DialContext in goroutine 28
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/dial.go:251 +0xccd

The Ip and Port I was using was: IP:  173.240.154.247        Port: 19200

**Comment by olebeck** [comment]
that pack is using an invalid manifest to try and stop this, nothing to do with the port, I'll make gophertunnel s manifest parsing more robust for this

**Comment by olebeck** [comment]
should now decode fine
