### ISSUE TITLE
this is the resource pack author trying to break decoding specifically to stop this.

### ISSUE THREAD

**Issue by HiveLanky** [bedrock-tool/bedrocktool#206]
You are unable to download realms for me im on the latest version and I click on worlds from the main menu then select realms and I choose my realm I want to see the world of. Then select Start join your localhost server then its just stuck on the loading screen and does not go off of it it pulls up a error on the gui. or the entire thing just closes.

time="2024-07-29T11:15:55-06:00" level=info msg="Bedrocktool Version 1.39.1-21" part=main
time="2024-07-29T11:16:04-06:00" level=info msg="Listening on [::]:19132"
time="2024-07-29T11:16:04-06:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-07-29T11:16:39-06:00" level=info msg="Connecting to 138.91.163.23:30052"
panic: read manifest: error decoding manifest JSON: hujson: line 16, column 1: parsing comment: unexpected EOF (data: {
    "format_version": 1,
    "header": {
        "description": "§gby Andiuber §bTwitter: §f@AndiuberOficial\n§9©TEAM CUBITOS MC §7www.cubitosmc.com",
        "name": "§cResource §l§gPlayer Model NPC §r§7v2.0",
        "uuid": "914350e8-9e9b-11ed-a8fc-0242ac120002",
        "version": [1, 0, 0]
    },
    "modules": [{
        "description": "",
        "type": "resources",
        "uuid": "9143543a-9e9b-11ed-a8fc-0242ac120002",
        "version": [1, 0, 0]
    }]
}
// \u0062\u0079 \u0041\u006e\u0064\u0069\u0075\u0062\u0065\u0072 \u00a9\u0054\u0045\u0041\u004d \u0043\u0055\u0042\u0049\u0054\u004f\u0053 \u004d\u0043 //)

goroutine 123 [running]:
github.com/sandertv/gophertunnel/minecraft/resource.MustReadPath(...)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/resource/pack.go:112
github.com/bedrock-tool/bedrocktool/utils/proxy.(*packCache).Get(0x1c57e80?, {0xc00130c870?, 0xc00130c870?}, {0xc000ced878?, 0x1d8c3c0?})
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/packcache.go:28 +0xce
github.com/bedrock-tool/bedrocktool/utils/proxy.(*rpHandler).OnResourcePacksInfo.func1({0xc00130c870, 0x24}, {0xc000ced878, 0x5}, {0x2fd9660, 0x0}, 0x82d3b)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/resourcepacks.go:170 +0x1a3
github.com/bedrock-tool/bedrocktool/utils/proxy.(*rpHandler).OnResourcePacksInfo(0xc000b62000, 0xc00113afc0)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/resourcepacks.go:285 +0x29f
github.com/sandertv/gophertunnel/minecraft.(*Conn).handlePacket(0xc0010f8008, {0x201b990, 0xc00113afc0})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:713 +0x48f
github.com/sandertv/gophertunnel/minecraft.(*Conn).handleMultiple(0xc0010f8008, {0xc0010a1210?, 0xc000ced6a0?, 0xc000c01380?})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:673 +0x85
github.com/sandertv/gophertunnel/minecraft.(*Conn).handle(0xc0010f8008, 0x5cb?)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:659 +0xb6
github.com/sandertv/gophertunnel/minecraft.(*Conn).receive(0xc0010f8008, {0xc00172aa08?, 0x0?, 0x0?})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:647 +0x19f
github.com/sandertv/gophertunnel/minecraft.listenConn(0xc0010f8008, 0xc000046300, 0xc0007166c0, 0xc000716720)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/dial.go:329 +0x1ea
created by github.com/sandertv/gophertunnel/minecraft.Dialer.DialContext in goroutine 16
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/dial.go:251 +0xccd

**Comment by olebeck** [comment]
please read errors when making titles, that lets me know what the issue actually is.
this is the resource pack author trying to break decoding specifically to stop this.
will fix

**Comment by olebeck** [comment]
should be fixed
