### ISSUE TITLE
`packs` Feature Blocked by Antipackstealing Plugin

### ISSUE THREAD

**Issue by NhanAZ** [bedrock-tool/bedrocktool#209]
#### Describe the Bug
The [Antipackstealing](https://github.com/Imjustnozell/Antipackstealing) plugin for the PocketMine-MP server is blocking the `packs` feature. I installed this plugin on my server, and it effectively disconnects players using the `packs` tool. However, it does not affect players using standard Minecraft clients, where the Resource Pack loads normally.

#### To Reproduce
1. Install the [Antipackstealing](https://github.com/Imjustnozell/Antipackstealing) plugin on [PocketMine-MP](https://github.com/pmmp/PocketMine-MP) server.
2. Attempt to join the server using the `packs` tool.
3. Observe the disconnection issue.

#### Expected Behavior
I expected the `packs` tool to function normally without being blocked by the Antipackstealing plugin.

#### Screenshots
![image](https://github.com/user-attachments/assets/9a694e76-1072-475b-a5a7-18181fdff5f2)

#### Desktop:
- **OS:** Windows
- **Version:** r1.39.1
- **Minecraft Version:** 1.21.2 (protocol version: 686)

#### Attach Files:
- [bedrocktool.log](https://github.com/user-attachments/files/16428462/bedrocktool.log)
- [packets.log](https://github.com/user-attachments/files/16428466/packets.log)
- [packets.log.gpg](https://github.com/NhanAZ/Stuff/raw/master/20h07_30-07-2024/packets.log.gpg)

**Comment by olebeck** [comment]
fixed
