### ISSUE TITLE
Crash bug when joining server

### ISSUE THREAD

**Issue by jameshackerbond** [bedrock-tool/bedrocktool#21]
**Describe the bug**
Bedrocktool crashes when trying to join server

**To Reproduce**
1. Open Bedrocktool and then type worlds
2. type in this IP: 
3. Join the server in MC
4. See errror

**Expected behavior**
It should download the world

**Error message**
--COPY FROM HERE--
time="2023-01-05T02:40:20Z" level=info msg="Version: v1.26.0-1-gd0ecf1c"
time="2023-01-05T02:40:20Z" level=info msg="Cmdline: [C:\\Users\\jbeza\\Downloads\\bedrocktool-v1.26.0-1-gd0ecf1c_windows_386.exe worlds]"
time="2023-01-05T02:40:20Z" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.4/x64/src/runtime/debug/stack.go:24 +0x83
main.main.func1()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:33 +0x21e
panic({0x8234e0, 0x11eda18})
        /opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x1ba
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldState).SaveAndReset(0x12df81e0)
        /home/runner/work/bedrocktool/bedrocktool/subcommands/world/world.go:343 +0x753
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldCMD).Execute(0x12408fc0, {0x9d58c0, 0x12dca0c0}, 0x12dca120, {0x0, 0x0, 0x0})
        /home/runner/work/bedrocktool/bedrocktool/subcommands/world/world.go:178 +0x2d7
github.com/google/subcommands.(*Commander).Execute(0x124880c0, {0x9d58c0, 0x12dca0c0}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x2d4
github.com/google/subcommands.Execute(...)
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:492
main.main()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:112 +0xc7b

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser ??
 - Version 11

**Additional context**

**Comment by olebeck** [comment]
custom server software with protections built in that are going to ban you and beeak the protocol library
