### ISSUE TITLE
Reconstruct world from replay

### ISSUE THREAD

**Issue by jedenastka** [bedrock-tool/bedrocktool#210]
**Is your feature request related to a problem? Please describe.**
I want to record a capture with `capture` to preserve all possible information about a world, but I'd also like to then be able to export said world just like with `worlds`. I saw there's a `-preload-replay` option, but it doesn't seem to work the way I'd expect it to.

```
$ ./bedrocktool -debug=true worlds -preload-replay=capture.pcap2
INFO[0000] Bedrocktool Version 1.39.1-26                 part=main
Enter Server: _INFO[0004] Reading replay capture.pcap2
```

This generates no worlds in the `worlds` directory. There's no clear documentation on what that option is supposed to do, but I figured it's intended to be used for something else, so this is a feature request, not a bug report. If I'm wrong, I can open a bug report instead.

**Describe the solution you'd like**
A `worlds` subcommand parameter such as `-from-capture=<filename>` that takes a capture file and reconstructs a world in the `worlds` directory, just like the `worlds` subcommand usually does.

**Describe alternatives you've considered**
Adding a `worlds` subcommand parameter that would also record a replay as it downloads the world. Sounds less convenient though.

**Additional context**
None.

**Comment by olebeck** [comment]
you put the filename of the pcap2 file as the address, preload is a more advanced feature that lets you do a live capture with a replay as base

**Comment by jedenastka** [comment]
Thanks, will close this now. This should definitely be documented, but it seems like the tool is lacking in documentation in general, unless I am missing something.
