### ISSUE TITLE
"rotation" and "mirror" keys from generated Skin Stealer geometry just broke

### ISSUE THREAD

**Issue by nextline0085** [bedrock-tool/bedrocktool#212]
**Describe the bug**
Generated Skin Stealer geometry doesn't save rotation and mirror data anymore. Looking into the generated **.JSON** file, the value of **rotation** key shows up as **null**, and **mirror** key just doesn't save anymore.
Tested on **The Hive** and **CubeCraft** servers, still have the following issue. Current fix of it is to use an older version of bedrocktool (1.37.0).

**Screenshots**
![Geometry_Issue](https://github.com/user-attachments/assets/bacc453b-3270-40a2-994b-b82a41e7e6a4)
![Geometry_Normal.png](https://github.com/user-attachments/assets/6072b346-6c24-49b4-b415-f84740d55313)

**Desktop:**
 - OS: Windows 10
 - Version: 1.39.1
 - Minecraft Version: 1.21.2.2

**Additional context**
Something surely broke when the program got a big cleaning code update related to geometry generator's part.

[Geometry_Issue.json](https://github.com/user-attachments/files/16449990/Geometry_Issue.json)
[Geometry_Normal.json](https://github.com/user-attachments/files/16449989/Geometry_Normal.json)
![Texture](https://github.com/user-attachments/assets/c184dec8-ea66-46da-bb5b-c83affe9a438)

**Comment by olebeck** [comment]
was missing from struct, should be fixed
