### ISSUE TITLE
Old protocol

### ISSUE THREAD

**Issue by wadudi82** [bedrock-tool/bedrocktool#221]
![image](https://github.com/user-attachments/assets/c941398f-b6a5-40d9-90a9-132db2e75948)

https://github.com/Sandertv/gophertunnel/commit/500a41a8f8c47d64201aa854a78ff703b1325dc9

I would appreciate it if u would update it

**Comment by olebeck** [comment]
done, there was quite a bit of merging to do in dragonfly.
should work fine havent had time to check alot of servers so please notify is something is wrong.

**Comment by wadudi82** [comment]
works great, thanks
