### ISSUE TITLE
Can not use multiple instances 

### ISSUE THREAD

**Issue by theaddonn** [bedrock-tool/bedrocktool#223]
It is not possible to create multiple instances of this tool, due to file access limitations.

For example if I try to download skins from server `A` (all without a proxy), then I can not download skins or other content from server B. That is because instance `A` locks the `token.json` which contains the xbox live credentials that instance `B` needs to read. This bug must have been introduced in one of the recent versions, since this did not happen using `1.37`.

I hope this bug gets fixed soon since it makes using the tool in a large scale quite hard.. well better put, just blatantly annoying.

**Comment by olebeck** [comment]
should be fixed, you will have to manually set different listen addresses of course, the issue was actually blobcache leveldb locking
solved by opening an in memory db for any instance past the first

**Comment by theaddonn** [comment]
thanks for fixing it :)
