### ISSUE TITLE
incompatible protocol - possible version mismatch

### ISSUE THREAD

**Issue by saadshield** [bedrock-tool/bedrocktool#224]
Downloading server not working as it's showing 
"listener conn: handle *packet.RequestNetworkSettings: incompatible protocol version: expected 729, got 748"

To Reproduce
1. Command cmd is  Bedrocktool worlds
2. Input command: - worlds
3. Enter Server: play.cubecraft.net
4. Connect to local ip - 192.168.x.x with default ports
5. Error showed in Minecraft - 
![image](https://github.com/user-attachments/assets/7a8dbe60-d44c-4f67-91b0-caaed8c48b07)
6. Error showed in cmd - 
'2024/10/26 22:51:41 listener conn: handle *packet.RequestNetworkSettings: incompatible protocol version: expected 729, got 748'
7. Retry connecting to local ip but another error showed saying already connected

Expected behavior
Download the worlds of cubecraft but met with unexpected error

Desktop
 - OS: windows
 - Bedrocktool Version 1.41.0-0
 - Minecraft Version 1.21.41

**Comment by olebeck** [comment]
update done, get r1.41.1 then it should work again
