### ISSUE TITLE
World Downloader doesnt work

### ISSUE THREAD

**Issue by xGAMEZAx** [bedrock-tool/bedrocktool#23]
i cant download most of the server maps, it just worked with hive and cube, also i wanted to test it for realms, i managed to get the ip and port of a realm but same issue.
![Captura de pantalla (360)](https://user-images.githubusercontent.com/120748737/211176974-24792818-1a1c-4c64-b1b4-f02415e7aee8.png)

**Comment by olebeck** [comment]
The error here is that it failed to login which I won't be able to replicate
