### ISSUE TITLE
Error when attempting to build manually

### ISSUE THREAD

**Issue by Hamsteroonie** [bedrock-tool/bedrocktool#230]
I'm not entirely sure whether this is the correct place to put this, but when attempting to build manually, it fails with the error:
gophertunnel\minecraft\conn.go:225:35: undefined: raknet.RakNetStatistics
gophertunnel\minecraft\conn.go:230:10: rk.Stats undefined (type *raknet.Conn has no field or method Stats)

1. Install all dependencies necessary for the build as shown in the github actions script (go, gogio, python, gitpython)
2. Install go dependencies (go get ./cmd/bedrocktool)
3. Run build.py

Expected behavior:
It should successfully build

Desktop:
 - OS: Windows
 - Version 1.42.0-0
 - Minecraft Version 1.21.50

**Comment by olebeck** [comment]
try `git submodule update --init`
