### ISSUE TITLE
World Downloader Chunk Bug

### ISSUE THREAD

**Issue by xGAMEZAx** [bedrock-tool/bedrocktool#26]
there is a bug with world donwloader sometimes chunks are broken, this was tested on a realm, also it works for other ones, but in some cases this happens with some realms. 
![Captura de pantalla (386)](https://user-images.githubusercontent.com/120748737/212603593-a88b6ad9-1126-441f-8a2e-fcab7ca28b04.png)
![Captura de pantalla (385)](https://user-images.githubusercontent.com/120748737/212603737-014cfc70-8a6e-46f6-aa38-cfb305583d2c.png)
i think that this might be happening because of custom blocks or that it cannot determine the version which is weird.

**Comment by xGAMEZAx** [comment]
i will be cool if you can add custom block support

**Comment by olebeck** [comment]
It happens because of custom blocks

**Comment by olebeck** [comment]
Custom blocks are now supported, however they require a behavior pack which needs to be generated and that code is early testing so it may or may not work perfectly

**Comment by xGAMEZAx** [comment]
> Custom blocks are now supported, however they require a behavior pack which needs to be generated and that code is early testing so it may or may not work perfectly

how can i generate it? the behavior pack
