### ISSUE TITLE
What planet are you on

### ISSUE THREAD

**Issue by ItsMwamOffi** [bedrock-tool/bedrocktool#31]
![image](https://user-images.githubusercontent.com/90533352/214114649-e1ef6349-68b5-4f8f-8bd5-24c138f90046.png)

**Comment by olebeck** [comment]
english is my sytem language so i didnt think to test for the case where there is another language than english, since there are no other languages than english in the world, fixed with update after i have discovered that there are other languages,,, apparently

**Comment by olebeck** [comment]
oh also this made me commit the custom blocks fix before i tested any more so try that i guess lol
