### ISSUE TITLE
error reading packet header: EOF

### ISSUE THREAD

**Issue by NhanAZ** [bedrock-tool/bedrocktool#32]
```
Input Command: packs
Enter Server: zeqa.net
time="2023-01-25T06:58:19+07:00" level=info msg="Connecting to zeqa.net:19132"
2023/01/25 06:58:33 error: error reading packet header: EOF
time="2023-01-25T06:58:33+07:00" level=error msg="dial minecraft 192.168.1.8:52400->31.25.11.41:19132: use of closed network connection"
time="2023-01-25T06:58:33+07:00" level=info msg="Press Enter to exit."
```

**Comment by olebeck** [comment]
Can't reproduce error, are you sure it wasn't a random disconnect or unreliable internet

**Comment by NhanAZ** [comment]
The tool works stably and doesn't get the same error in other servers.

**Comment by NhanAZ** [comment]
I'm pretty sure this is a tool issue. I tried loading the server's resource pack on another tool and it worked.

**Comment by olebeck** [comment]
can you run it with debug,
`-debug packs`

**Comment by NhanAZ** [comment]
```
Input Command: -debug packs
Enter Server: zeqa.net
time="2023-01-26T12:43:42+07:00" level=info msg="Connecting to zeqa.net:19132"
time="2023-01-26T12:43:47+07:00" level=debug msg="\x1b[36mC\x1b[0m->\x1b[32mS\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2023-01-26T12:43:57+07:00" level=error msg="*packet.TakeItemActor: %!w(*errors.errorString=&{EOF})"
2023/01/26 12:43:57 error: error reading packet header: EOF
time="2023-01-26T12:43:57+07:00" level=error msg="dial minecraft 192.168.1.3:62447->31.25.11.41:19132: use of closed network connection"
time="2023-01-26T12:43:57+07:00" level=info msg="Press Enter to exit."
```

**Comment by olebeck** [comment]
![Screenshot_20230126_153803](https://user-images.githubusercontent.com/31539311/214863887-628fa8b6-f178-4e2a-8779-e15a94a0fe0c.png)
thats a very weird thing for it to break on, its a simple packet.
it maybe a compression issue????

**Comment by olebeck** [comment]
after RequestNetworkSettings there is supposed to be compression on all packets that could be the issue

**Comment by olebeck** [comment]
just added a new feature for more debugging, can you please update and run `-extra-debug worlds`
and then upload the packets.log.enc file here so i can look at what the packets being sent look like

**Comment by NhanAZ** [comment]
```
Input Command: -extra-debug worlds
Enter Server: zeqa.net
time="2023-01-27T19:24:17+07:00" level=info msg="failed to translate! refreshed_token"
time="2023-01-27T19:24:17+07:00" level=info msg="Listening on [::]:19132"
time="2023-01-27T19:24:17+07:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2023-01-27T19:25:39+07:00" level=info msg="Connecting to zeqa.net:19132"
2023/01/27 19:25:52 error: error reading packet header: EOF
time="2023-01-27T19:25:52+07:00" level=error msg="failed to connect to zeqa.net:19132: dial minecraft 192.168.1.3:52940->31.25.11.41:19132: use of closed network connection"
time="2023-01-27T19:25:52+07:00" level=info msg="Press Enter to exit."
```
`packets.log.enc`: https://cdn.discordapp.com/attachments/984172021061673101/1068507590801227946/packets.log.enc

**Comment by UnknxwnXBL** [comment]
> ```
> Input Command: -extra-debug worlds
> Enter Server: zeqa.net
> time="2023-01-27T19:24:17+07:00" level=info msg="failed to translate! refreshed_token"
> time="2023-01-27T19:24:17+07:00" level=info msg="Listening on [::]:19132"
> time="2023-01-27T19:24:17+07:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
> time="2023-01-27T19:25:39+07:00" level=info msg="Connecting to zeqa.net:19132"
> 2023/01/27 19:25:52 error: error reading packet header: EOF
> time="2023-01-27T19:25:52+07:00" level=error msg="failed to connect to zeqa.net:19132: dial minecraft 192.168.1.3:52940->31.25.11.41:19132: use of closed network connection"
> time="2023-01-27T19:25:52+07:00" level=info msg="Press Enter to exit."
> ```
> 
> `packets.log.enc`: https://cdn.discordapp.com/attachments/984172021061673101/1068507590801227946/packets.log.enc

Just copy the ip it spits out afterwards and use that instead. So use "31.25.11.41" this instead of "zeqa.net".
I had the same issue and that's how I fixed it.

**Comment by NhanAZ** [comment]
It doesn't work for me
```
Input Command: packs
Enter Server: 31.25.11.41
time="2023-01-27T23:30:58+07:00" level=info msg="Connecting to 31.25.11.41:19132"
2023/01/27 23:31:11 error: error reading packet header: EOF
time="2023-01-27T23:31:11+07:00" level=error msg="dial minecraft 192.168.1.3:60989->31.25.11.41:19132: use of closed network connection"
time="2023-01-27T23:31:11+07:00" level=info msg="Press Enter to exit."
```

**Comment by olebeck** [comment]
you didnt actually run with `-extra-debug packs`

**Comment by olebeck** [comment]
please update and run agian, there was a a problem where it didnt enable packet logging if only extra-debug is used note the filename has changed to packets.log.gpg

**Comment by NhanAZ** [comment]
Great it worked at the latest release [v1.26.1](https://github.com/bedrock-tool/bedrocktool/releases/tag/v1.26.1)
Do you still need `packets.log.gpg`?

**Comment by NhanAZ** [comment]
[packets.log.gpg](https://cdn.discordapp.com/attachments/984172021061673101/1069147354369892352/packets.log.gpg)

**Comment by olebeck** [comment]
its just using regular compression that time so i think it may be the alternative compression algorithm breaking, if you get this issue again please generate a log so i can verify that that is the issue.
