### ISSUE TITLE
"Unknown" Custom Blocks in the saved world.

### ISSUE THREAD

**Issue by xLayerS37** [bedrock-tool/bedrocktool#34]
Custom blocks in worlds you save from a server are transformed into the "Unknown Block"
I have applied all of the server resource packs to the world.

**To Reproduce**
1. Download a world from a server with custom blocks.
2. Go to the place where custom blocks were on the server.

**Expected behavior**
The custom blocks should look like they do on the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/123593515/214680827-4b6e7292-f0b7-4109-8b71-34f72e750e3e.png)

**Comment by olebeck** [comment]
you need to enable creator holiday experiments to use custom blocks on bedrock.
tool is supposed to automatically do this, it wasnt due to a bug.
