### ISSUE TITLE
World downloading crashes when switching between worlds

### ISSUE THREAD

**Issue by downigamer** [bedrock-tool/bedrocktool#36]
When switching between worlds in certain servers with custom blocks (ex. Cubecraft) Bedrocktool closes down and doesn't save anything

**Comment by downigamer** [comment]
Saving of behaviour packs and resource packs works, but the app closes when switching between worlds

**Comment by downigamer** [comment]
UPDATE: world spawned full of beds, mangrove propagules and saved the wrong blocks from spawn

**Comment by olebeck** [comment]
which server

**Comment by downigamer** [comment]
cubecraft

**Comment by olebeck** [comment]
found source of the issue looking for what broke

**Comment by olebeck** [comment]
new update should fix both issues
