### ISSUE TITLE
Certain blocks are swapped / changed after being world downloaded

### ISSUE THREAD

**Issue by downigamer** [bedrock-tool/bedrocktool#37]
Certain blocks are swapped with other blocks, different rotations of themselves or removed entirely as shown here
(cubecraft, again)
SERVER (original)
![image](https://user-images.githubusercontent.com/45134430/215360873-45189f6c-abf2-4e94-b74c-22327c61a942.png)
![image](https://user-images.githubusercontent.com/45134430/215360909-d7f42d3e-9316-4bca-bd40-637cb5b6fc4e.png)
![image](https://user-images.githubusercontent.com/45134430/215360924-d8cc4c79-eb3a-4e31-b377-f1d014e91dc9.png)
![image](https://user-images.githubusercontent.com/45134430/215360937-d41e7637-7285-49b1-81b8-475fc858c6aa.png)
![image](https://user-images.githubusercontent.com/45134430/215360946-2184351c-b545-4e34-b15e-fd9b06d08faf.png)
![image](https://user-images.githubusercontent.com/45134430/215360962-5fd33198-6a1d-49fa-93fa-d47270883a95.png)
LOCAL (world file that was downloaded)
![image](https://user-images.githubusercontent.com/45134430/215360980-2b6abef7-5f86-4a86-b703-05b7a47b9349.png)
![image](https://user-images.githubusercontent.com/45134430/215360996-95e85456-97e1-40cd-a9d0-28669163c778.png)
![image](https://user-images.githubusercontent.com/45134430/215361004-23e51b6d-7be9-435b-b549-882866e8bdc8.png)
![image](https://user-images.githubusercontent.com/45134430/215361017-01c3de64-5815-4da3-8d7d-ebc4c5df3c00.png)

**Comment by olebeck** [comment]
hm that is the exact same bug again

**Comment by downigamer** [comment]
yes, but not as big this time, instead of huge swaps and random blocks being replaced with others, now its smaller happens with other blocks that are not as noticeable when one first spawns

**Comment by downigamer** [comment]
it seems to only happen to certain blocks, here is a list of the current ones i have
endstone was turned into crimson doors
cobblestone was turned into poppys
downward stair rotations are reset / turned into cakes with candles
gray wool and carpets turned into cyan wool and carpets
redstone rotations turning into exposed copper

**Comment by olebeck** [comment]
the game stores blocks as a list and where in the list a certain block is defines its number, the numbers change when custom blocks are added and that is something im still doing wrong on the new format, old format (hive for example) works fine.

**Comment by djcjxd** [comment]
what if you just store the custom blocks towards the end of the list or just make a flag to disable saving custom blocks?

**Comment by olebeck** [comment]
the order of the list is defined by minecraft, if its wrong this issue
appears

**Comment by AhmedSalih122** [comment]
this bug getting reparied?

**Comment by olebeck** [comment]
issue should now be fixed, reopen if not.
