### ISSUE TITLE
world doesn't download

### ISSUE THREAD

**Issue by trwpp** [bedrock-tool/bedrocktool#38]
![Captura de pantalla (177)](https://user-images.githubusercontent.com/88416857/216751307-1187642b-4894-461b-a0bf-c200567373b1.png)

**Comment by olebeck** [comment]
The error suggests that your system clock is set wrong can you check that it's not slightly behind real time?

**Comment by trwpp** [comment]
> The error suggests that your system clock is set wrong can you check that it's not slightly behind real time?

worked
