### ISSUE TITLE
unable to connect to pixel paradise

### ISSUE THREAD

**Issue by BerLeo** [bedrock-tool/bedrocktool#39]
Hi, with Fiddler I found the address for PIxel Paradise, play.pixelparadise.gg.
I can't get bedrocktool to connect to it though. The packs command won't connect. The worlds command won't connect.
enabling preload for the worlds command doesn't change anything.

Although, since the first thing I tried to connect with was a cheat client (to try to get the server address that way), maybe they banned my device id. I can still connect to them with my tablet though.
Can't connect to them on my win11 laptop with unmodded minecraft. unsure if banned or if this is currently normal behavior.

**Comment by olebeck** [comment]
bug with custom blocks causing a crash will try fix

**Comment by olebeck** [comment]
new version should have fixed this, if it hasnt reopen the issue, thanks.

**Comment by BerLeo** [comment]
bedrocktool -debug=true debug-proxy -address play.pixelparadise.gg
time="2023-02-05T10:03:28-05:00" level=info msg="Bedrocktool Version v1.26.1-1-ga601cb3"
time="2023-02-05T10:03:28-05:00" level=info msg="Listening on [::]:19132"
time="2023-02-05T10:03:28-05:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2023-02-05T10:04:10-05:00" level=info msg="Connecting to play.pixelparadise.gg:19132"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x8f, packet.NetworkSettings"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x01, packet.Login"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x03, packet.ServerToClientHandshake"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x04, packet.ClientToServerHandshake"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x02, packet.PlayStatus"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x81, packet.ClientCacheStatus"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x06, packet.ResourcePacksInfo"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x07, packet.ResourcePackStack"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"

bedrocktool -preload=true -debug=true debug-proxy -address play.pixelparadise.gg
time="2023-02-05T10:06:35-05:00" level=info msg="Bedrocktool Version v1.26.1-1-ga601cb3"
time="2023-02-05T10:06:36-05:00" level=info msg="Preloading Resourcepacks"
time="2023-02-05T10:06:36-05:00" level=info msg="Connecting to play.pixelparadise.gg:19132"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x8f, packet.NetworkSettings"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x01, packet.Login"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x03, packet.ServerToClientHandshake"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x04, packet.ClientToServerHandshake"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x02, packet.PlayStatus"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x81, packet.ClientCacheStatus"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x06, packet.ResourcePacksInfo"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x52, packet.ResourcePackDataInfo"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x54, packet.ResourcePackChunkRequest"
