### ISSUE TITLE
Bug "Worlds"

### ISSUE THREAD

**Issue by NetureCrafter** [bedrock-tool/bedrocktool#4]
**Describe the bug:**
Flowers, tulips and seeds are not planted

**Screenshots:**
![Screenshot (761)](https://user-images.githubusercontent.com/96377600/187419432-e8c67534-825e-4e1e-9612-51951509704b.png)

**Desktop:**
 - OS: Windows 10

**Comment by olebeck** [comment]
thats due to the blocks updating when the world is run by the internal server in minecraft bedrock, im not sure if theres a way to prevent block updates entirely within the normal server.
it is possible to run a customized server that doesnt tick the world at all though
