### ISSUE TITLE
Connection issues.

### ISSUE THREAD

**Issue by BerLeo** [bedrock-tool/bedrocktool#40]
Hi, again. This is for PIxel Paradise. Your fix didn't fix it for me.
When I open it in regular minecraft with no proxy I get to a screen where it says it's downloading a resource pack and it stays at 0.0MB/2.4MB before saying unable to connect or something similar.
This is what I get from Bedrocktool.
bedrocktool -debug=true debug-proxy -address play.pixelparadise.gg
time="2023-02-05T10:03:28-05:00" level=info msg="Bedrocktool Version v1.26.1-1-ga601cb3"
time="2023-02-05T10:03:28-05:00" level=info msg="Listening on [::]:19132"
time="2023-02-05T10:03:28-05:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2023-02-05T10:04:10-05:00" level=info msg="Connecting to play.pixelparadise.gg:19132"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x8f, packet.NetworkSettings"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x01, packet.Login"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x03, packet.ServerToClientHandshake"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x04, packet.ClientToServerHandshake"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x02, packet.PlayStatus"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x81, packet.ClientCacheStatus"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x06, packet.ResourcePacksInfo"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x07, packet.ResourcePackStack"
time="2023-02-05T10:04:12-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"

bedrocktool -preload=true -debug=true debug-proxy -address play.pixelparadise.gg
time="2023-02-05T10:06:35-05:00" level=info msg="Bedrocktool Version v1.26.1-1-ga601cb3"
time="2023-02-05T10:06:36-05:00" level=info msg="Preloading Resourcepacks"
time="2023-02-05T10:06:36-05:00" level=info msg="Connecting to play.pixelparadise.gg:19132"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x8f, packet.NetworkSettings"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x01, packet.Login"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x03, packet.ServerToClientHandshake"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x04, packet.ClientToServerHandshake"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x02, packet.PlayStatus"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x81, packet.ClientCacheStatus"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x06, packet.ResourcePacksInfo"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x52, packet.ResourcePackDataInfo"
time="2023-02-05T10:06:37-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x54, packet.ResourcePackChunkRequest"

I have another address here but I can't remember which server it's from. maybe lifeboat. I tried to get the "adopt a pet" world from there.
The 'lobby' (mco.lbsg.net) server works alright but when I connect to this one it gives a similar problem.
bedrocktool -preload=true -debug=true worlds -address lbc.lbsg.net
time="2023-02-05T10:29:42-05:00" level=info msg="Bedrocktool Version v1.26.1-1-ga601cb3"
time="2023-02-05T10:29:43-05:00" level=info msg="Preloading Resourcepacks"
time="2023-02-05T10:29:43-05:00" level=info msg="Connecting to lbc.lbsg.net:19132"
time="2023-02-05T10:29:45-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2023-02-05T10:29:45-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x8f, packet.NetworkSettings"
time="2023-02-05T10:29:45-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x01, packet.Login"
time="2023-02-05T10:29:45-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x03, packet.ServerToClientHandshake"
time="2023-02-05T10:29:45-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x04, packet.ClientToServerHandshake"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x02, packet.PlayStatus"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x81, packet.ClientCacheStatus"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x06, packet.ResourcePacksInfo"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x52, packet.ResourcePackDataInfo"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x52, packet.ResourcePackDataInfo"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x54, packet.ResourcePackChunkRequest"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x52, packet.ResourcePackDataInfo"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x54, packet.ResourcePackChunkRequest"
time="2023-02-05T10:29:46-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x54, packet.ResourcePackChunkRequest"

bedrocktool -debug=true debug-proxy -address lbc.lbsg.net
time="2023-02-05T10:38:38-05:00" level=info msg="Bedrocktool Version v1.26.1-1-ga601cb3"
time="2023-02-05T10:38:39-05:00" level=info msg="Listening on [::]:19132"
time="2023-02-05T10:38:39-05:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2023-02-05T10:38:45-05:00" level=info msg="Connecting to lbc.lbsg.net:19132"
time="2023-02-05T10:38:47-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0xc1, packet.RequestNetworkSettings"
time="2023-02-05T10:38:47-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x8f, packet.NetworkSettings"
time="2023-02-05T10:38:47-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x01, packet.Login"
time="2023-02-05T10:38:47-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x03, packet.ServerToClientHandshake"
time="2023-02-05T10:38:47-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x04, packet.ClientToServerHandshake"
time="2023-02-05T10:38:48-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x02, packet.PlayStatus"
time="2023-02-05T10:38:48-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x81, packet.ClientCacheStatus"
time="2023-02-05T10:38:48-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x06, packet.ResourcePacksInfo"
time="2023-02-05T10:38:48-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"
time="2023-02-05T10:38:48-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x07, packet.ResourcePackStack"
time="2023-02-05T10:38:48-05:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x08, packet.ResourcePackClientResponse"

Unlike Pixel Paradise, I can directly connect to the adopt-a-pet world of LIfeBoat.

**Comment by olebeck** [comment]
server seems to just not be sending resourcepack data, weird.

**Comment by olebeck** [comment]
this issue seems to now be fixed, if you still have it feel free to reopen and give extra info.
