### ISSUE TITLE
resource packs download error

### ISSUE THREAD

**Issue by 1111qqjzja** [bedrock-tool/bedrocktool#41]
pack had a different size in the resourcepackinfo packet than the resourcepackdatainfo packet
![@3D542MTBF`Y7ICSB{GV4CL(1)](https://user-images.githubusercontent.com/89286242/217025769-e0e2c60f-beca-485c-ab14-1c2ec2d0ba3f.png)

**Comment by olebeck** [comment]
this is a warning about the server sending an incorrect field, it doesnt stop the download from working you just need to wait for it to finish after this.
