### ISSUE TITLE
Resource pack not loaded if server is whitelisted

### ISSUE THREAD

**Issue by NhanAZ** [bedrock-tool/bedrocktool#44]
In Minecraft you can download resource packs even if the server is whitelisted and bedrocktool cannot download resource packs if the server is whitelisted.
For example the server `play.askills.xyz`. This is what I get:
```
Input Command: -extra-debug packs
Enter Server: play.askills.xyz
time="2023-02-22T20:52:42+07:00" level=info msg="Connecting to play.askills.xyz:19132"
[debug packets see all in packets.log]
time="2023-02-22T20:54:01+07:00" level=info msg="Disconnect {false Server is whitelisted}"
time="2023-02-22T20:54:01+07:00" level=debug msg="\x1b[32mS\x1b[0m->\x1b[36mC\x1b[0m 0x05, packet.Disconnect"
time="2023-02-22T20:54:01+07:00" level=error msg="failed to connect to play.askills.xyz:19132: dial minecraft 192.168.1.12:60572->212.87.213.113:19132: Server is whitelisted"
time="2023-02-22T20:54:01+07:00" level=info msg="Press Enter to exit."
```
[packets.log](https://cdn.discordapp.com/attachments/1007656285853990912/1077953716482744340/packets.log)
[packets.log.gpg](https://cdn.discordapp.com/attachments/1007656285853990912/1077953716801523783/packets.log.gpg)

**Comment by olebeck** [comment]
fixed this with latest release
