### ISSUE TITLE
Device ID Grabber

### ISSUE THREAD

**Issue by Furzide** [bedrock-tool/bedrocktool#46]
A command or proxy to grab the device id of specific players and log them to a file would be a very useful feature.

**Comment by Furzide** [comment]
Oh and also an option to change your device id to a specific one would be awesome

**Comment by olebeck** [comment]
the device id is sensibly stripped on most servers, i dont see a reason to add that except abuse/stalking.
changing deviceID can be done now using -userdata <customdata.json file> after any subcommand that supports it and filling it in as you want to
