### ISSUE TITLE
Enhance The Geometry Stealer 

### ISSUE THREAD

**Issue by StrafeYourself** [bedrock-tool/bedrocktool#49]
So, right now with the geometry stealer is really awful and does do what we want but really inefficiently. So, how you might ask? Well when you load into a server it will download the skins with geometry however, it also downloads the skins that are just default server replacement skins that can appear on the hive if you are waring a invalid skin that has custom geometry that as not been accept by the hive! However, that's not the worst part, so what is that part you might ask? Well, it downloads the skins that it see's and it gets the geo id , player id and the player uuid to add it to skins download however, if we rerender the players with the exact same default skin witch please just get rid of that btw, but the geometry meaning it does not check to see if the model has already been downloaded meaning it will continue to download the exact same players skins and geometry meaning it keeps downloading the skins we already have leading to multiple copies of the exact same skin we already got. But in a new folder like this.
uuid
uuid (2)
So how can we fix this? Well, make it so it only downloads skins with geometry and capes and if it detects a person with a geometry id it will save, the folder, image and the geometry file as the geometry id name meaning if they change there skin to a different costume the different costume will have a different geometry id meaning it will no longer lead to large amounts of duplicates wile also making it much easy for the person to find the skin they downloaded. So since I am a bad explainer I will try sum it down and make it much more easier for you to under stand. So for example: it downloads the first persons skin and geometry id was geometry.humanoid.custom and it saved the imagen, geo files and folder as the geo name. But if the exact same person changed there skin to a different costume and if it detects a different geometry id witch in this example is geometry.humanoid.customSlim it will check to see if folder, image, geometry file, with the exact same geo id name has already been downloaded if not it will once again download and save the folder, image, geometry file as the geo id name.

**Comment by olebeck** [comment]
there are already checks for duplicate skins, can you send a zip of a folder with this issue?

**Comment by StrafeYourself** [comment]
Ok thank you I will take a double look.

**Comment by olebeck** [comment]
should be implemented now, if theres something still missing open a new issue with a suggestion
