### ISSUE TITLE
16 Bit?!

### ISSUE THREAD

**Issue by BerLeo** [bedrock-tool/bedrocktool#50]
This version of C:\apps\BlueTool\bedrocktool.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

![image](https://user-images.githubusercontent.com/28075586/223720023-63162be6-5018-43f8-9586-3c47389b580a.png)

**Comment by olebeck** [comment]
can you try the new version and see if this is still a problem

**Comment by BerLeo** [comment]
Sorry, I'm a rather busy person.
I tried the new one, same issue.

**Comment by olebeck** [comment]
bug fixed, new version solves it
