### ISSUE TITLE
Can't mirror worlds from ... a realm.

### ISSUE THREAD

**Issue by BerLeo** [bedrock-tool/bedrocktool#52]
Hi, it's me again.
It'll connect to the realm but it just keeps spitting out
`time="2023-03-10T06:48:34-05:00" level=error msg="The server didnt send the chunk before the subchunk!"`
So I'm running around with the map blank and the message at the bottom telling me "0 chunks loaded"

this is with the CLI version.
It does work with the servers I can connect to.

**Comment by olebeck** [comment]
Fixed in the new version, was a wrong if in the saving logic
