### ISSUE TITLE
Saving worlds from CubeCraft doesn't work properly and crashes the game

### ISSUE THREAD

**Issue by downigamer** [bedrock-tool/bedrocktool#56]
As mentioned in #55 the game is crashed upon opening a world that is saved from cubecraft, with the preview of the map simply just turning into a pink map

**Comment by olebeck** [comment]
#54 known issue due to 1.19.70 being an unexpected update that changed block states in a way that's nor implemented yet

**Comment by StrafeYourself** [comment]
Ok thanks for letting us know olebeck.

**Comment by olebeck** [comment]
fixed with r1.28.0
