### ISSUE TITLE
Failed to connect to Mineplex

### ISSUE THREAD

**Issue by BJTMastermind** [bedrock-tool/bedrocktool#58]
**Describe the bug**
The bedrocktool fails to connect to mineplex and throws this error message: 
```
INFO[0000] Bedrocktool Version 1.27.0-26                
INFO[0000] Preloading Resourcepacks                     
INFO[0000] Connecting to mco.mineplex.com:19132         
2023/03/18 16:56:54 error: verify claims: square/go-jose: error in cryptographic primitive
ERRO[0002] failed to connect to mco.mineplex.com:19132: dial minecraft <My IP>:35370->108.178.12.128:19132: use of closed network connection
```

**To Reproduce**
1. Run the following command `./bedrocktool -preload=true worlds -address mco.mineplex.com -image -inv -packs`
2. See error

**Expected behavior**
The tool would connect to mineplex like normal so I can download the world.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Tool Version 1.27.0-26 (Latest Version)

**Comment by olebeck** [comment]
this has been a known issue with the underlying connection library (gophertunnel) because mineplex weirdly implements the protocol for that, not that much i can do about that unless i have some pointers for what is actually going wrong with their implementation

**Comment by BJTMastermind** [comment]
oh ok didn't know it was a known issue.
