### ISSUE TITLE
Entity swapping when downloading The Hive's Arcade hub.

### ISSUE THREAD

**Issue by fourcandy** [bedrock-tool/bedrocktool#60]
The entities in the hive arcade hub are being swapped when I download them with resource packs. Some screenshots are given below.
![image](https://user-images.githubusercontent.com/56483324/226669316-fb57a175-196d-474e-bffd-7aabe381d522.png)
In the above image, BlockDrop NPC has been swapped with TreasureWars NPC. Capture the Flag with Murder Mystery. The Bridge with Skywars and Groudwars with Skywars Kits. Also, the Block Party NPC and Hologram (The title of the game above the NPC) has been replaced with two animal entities. All of the swapped entities are from The Hive's main hub.
More images with such replacements.
![image](https://user-images.githubusercontent.com/56483324/226670396-bc58b08a-b986-48a6-8fce-4afd75e5f591.png)
![image](https://user-images.githubusercontent.com/56483324/226670823-051f2585-acbf-417f-9ab7-041d6eac2023.png)
![image](https://user-images.githubusercontent.com/56483324/226670889-112bff8a-ebb4-4a9e-a8de-37f8c0e368f5.png)
The issue doesn't happen in the main hub. Just the arcade one.
World download if you need it (its only the spawn of the arcade hub). Convert the .zip into a .mcworld (GitHub doesn't support .mcworld)
[world-1.zip](https://github.com/bedrock-tool/bedrocktool/files/11030931/world-1.zip)

**Comment by olebeck** [comment]
the issue is that the entities table wasnt being reset properly when switching worlds so entities from previous worlds show up in the next one, that should now reset correctly
