### ISSUE TITLE
Remove duplicate skins

### ISSUE THREAD

**Issue by qtqtpie** [bedrock-tool/bedrocktool#61]
Skins option downloads the same skin repeatedly even from the same user and appends an increment to the filename. There are also multiple users that have the exact same skin and would prefer not to download duplicates.

I'd like an option to download only unique skins. Or functionality to search and remove duplicates when the listener is no longer running.
![image](https://user-images.githubusercontent.com/128836042/227604219-112f5767-ddad-497d-ba81-7210e32b5923.png)

**Comment by olebeck** [comment]
can you send that folder so i can see why theyre not being detected as duplicates

**Comment by qtqtpie** [comment]
Added additional samples, these are all NPCs the 2 additional have identical geometry files , it happens for players as well but I didn't want to send usernames of other players and whatnot
[Calico.zip](https://github.com/bedrock-tool/bedrocktool/files/11066629/Calico.zip)
[hub_quest_master_npc_name.zip](https://github.com/bedrock-tool/bedrocktool/files/11066645/hub_quest_master_npc_name.zip)
[hub_quest_master_name_tp.zip](https://github.com/bedrock-tool/bedrocktool/files/11066646/hub_quest_master_name_tp.zip)

**Comment by olebeck** [comment]
should now be working properly
