### ISSUE TITLE
Blocks lose their data sometimes (Hive Server)

### ISSUE THREAD

**Issue by BJTMastermind** [bedrock-tool/bedrocktool#68]
**Describe the bug**
When downloading a world from the Hive (haven't tried other servers) some blocks like Signs, Banners, and maybe more seem to lose their data sometimes. Signs will sometimes lose their text, Banners will sometimes lose their patterns. See images below.

**To Reproduce**
1. Play a mini game on Hive that has signs or banners in it like Death Run.
2. Download the world.
3. Open the download world in singleplayer.
4. See some signs and banners missing their data.

**Expected behavior**
All signs and Banners in the downloaded world are accurate to what they look like on the server.

**Screenshots**
<details>
<b>On Server:</b>
<img src=https://user-images.githubusercontent.com/18742837/233466621-3d65d7de-446e-4043-9c67-b2d82849fa1d.png>
<b>In Singleplayer:</b>
<img src=https://user-images.githubusercontent.com/18742837/233466910-d8a2ddec-f42b-4413-9d8b-76e141d7d4bf.png>
<b>On Server:</b>
<img src=https://user-images.githubusercontent.com/18742837/233467157-eb8d8288-1c2c-4a40-ad53-b0c0cdb7394d.png>
<b>In Singleplayer:</b>
<img src=https://user-images.githubusercontent.com/18742837/233467224-e4300d4f-02ef-43fc-a0b5-498e66b250f0.png>
<b>On Server (Example of it sometimes working):</b>
<img src=https://user-images.githubusercontent.com/18742837/233467287-ba6185aa-ec3d-401b-9d97-50ca0126f2d2.png>
<b>In Singleplayer (Example of it sometimes working):</b>
<img src=https://user-images.githubusercontent.com/18742837/233467331-8818d9ba-4fe6-4384-8e21-09d09be1d3d9.png>
</details>

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04 (Linux)
 - Version: 1.28.0-37
 - Minecraft Version: 1.19.73.02

**Additional context**

**attach packets.log.gpg (not always necessary)**
this file can be helpful for debugging without having to connect to the server.
it can be created by running with -extra-debug [e.g. bedrocktool.exe -extra-debug worlds -address play.mojang.com ]
be sure to only attach the .gpg file which is not publicly readable.

**Comment by olebeck** [comment]
my guess is that its a bug with how blocknbt are stored in a list inside a subchunk, so i changed that to be per block now, see if it works more reliably now

**Comment by BJTMastermind** [comment]
The issue seems to still exist after updating to bedrocktool-1.28.0-42 and redownloading the world.

**Comment by olebeck** [comment]
this was a long standing bug, (an if instead of a for loop in decode) meaning that only the first blocknbt per chunk was decoded and saved, it should be fixed now.
reopen if issue is still there

**Comment by BJTMastermind** [comment]
Looks perfect now. Keep up the great work with this amazing tool!
