### ISSUE TITLE
Pack-Downloader isn't working on CubeCraft

### ISSUE THREAD

**Issue by NetureCrafter** [bedrock-tool/bedrocktool#69]
**Describe the bug**
Pack-Downloader isn't working on CubeCraft

**Expected behavior**
level=error msg="Connection to play.cubecraft.net:19132 failed: dial minecraft IP ->IP: Exception Connecting:DecoderException : java.lang.IllegalStateException: Invalid frame ID: 253 @ io.netty.handler.codec.MessageToMessageDecoder:98"

**Desktop (please complete the following information):**
 - Windows 10

**Comment by olebeck** [comment]
issue seems specific to play.cubecraft.net, mco.cubecraft.net doesnt have this problem so you could use that.
problem is on the server so cant say for sure what is broken.

**Comment by NetureCrafter** [comment]
> issue seems specific to play.cubecraft.net, mco.cubecraft.net doesnt have this problem so you could use that. problem is on the server so cant say for sure what is broken.

Alright, thank you
