### ISSUE TITLE
Packs command bug

### ISSUE THREAD

**Issue by RealYXNG** [bedrock-tool/bedrocktool#7]
--COPY FROM HERE--
time="2022-11-21T10:37:28+04:00" level=info msg="Version: v1.24.12"
time="2022-11-21T10:37:28+04:00" level=info msg="Cmdline: [bedrocktool-v1.24.12_windows_amd64.exe packs]"
time="2022-11-21T10:37:28+04:00" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
main.main.func1()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:32 +0x199
panic({0x115fc20, 0x1b488e0})
        /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
github.com/bedrock-tool/bedrocktool/utils.(*Pack).Decrypt(0xc0003af9f0)
        /home/runner/work/bedrocktool/bedrocktool/utils/resourcepack.go:115 +0x6d2
github.com/bedrock-tool/bedrocktool/utils.(*ResourcePackCMD).Execute(0xc000008318, {0x136d5d8, 0xc0000a9440}, 0xc0007d7cf0?, {0xb0c867?, 0x23d7916fe68?, 0x18?})
        /home/runner/work/bedrocktool/bedrocktool/utils/resourcepack.go:254 +0x9e5
github.com/google/subcommands.(*Commander).Execute(0xc000160080, {0x136d5d8, 0xc0000a9440}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x3bc
github.com/google/subcommands.Execute(...)
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:492
main.main()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:110 +0xaef

--END COPY HERE--

Steps:

Run the "packs" command and the server IP is "play.nethergames.org".

**Comment by olebeck** [comment]
issue was due to missing files in the resourcepack, new update added a warning for that and doesnt crash
