### ISSUE TITLE
Jwt token error

### ISSUE THREAD

**Issue by lnwAitJi** [bedrock-tool/bedrocktool#70]
**Describe the bug**
error: parse login request: validate token 2: square/go-jose/jwt: validation field, token issued in the future (iat)
**To Reproduce**
join the server
**Expected behavior**
can join without error
**Desktop (please complete the following information):**
 - OS: [e.g. windows
 - Version [e.g. 1.29.0]
 - Minecraft Version [e.g. 1.19.81]
 
 ![Screenshot](https://user-images.githubusercontent.com/100911929/235333419-49cc3890-3286-4f45-b120-2deabdf7d1c3.png)

**Comment by olebeck** [comment]
your computers time is likely set wrong
