### ISSUE TITLE
Biomes extend past their original boarders in downloaded world (Hive Server)

### ISSUE THREAD

**Issue by BJTMastermind** [bedrock-tool/bedrocktool#72]
**Describe the bug**
After downloading a world that has multiple biomes some biomes seem to extend past their original boarder from on the server

**To Reproduce**
1. Go on to the Hive
2. Play DeathRun
3. Download the deathrun map "Survival"
4. Load world in singleplayer and see that the nether biome has extended into another part of the map causing water to be red in a parts of the map that it shouldn't be. (Issue appears at the turn in the cave you first enter near the beginning of the map)

**Expected behavior**
The biome boarders match what they are on the server.

**Screenshots**
<details>
    <p>On Server</p>
    <img src=https://github.com/bedrock-tool/bedrocktool/assets/18742837/4c577671-9b11-4049-9210-5e26c380cd2b>
    <p>In Singleplayer</p>
    <img src=https://github.com/bedrock-tool/bedrocktool/assets/18742837/7f122c72-6b8a-40df-a876-59526abd9858>
</details>

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04 (Linux)
 - Version: 1.29.0-2
 - Minecraft Version: 1.19.83

**Additional context**

**attach packets.log.gpg (not always necessary)**
this file can be helpful for debugging without having to connect to the server.
it can be created by running with -extra-debug [e.g. bedrocktool.exe -extra-debug worlds -address play.mojang.com ]
be sure to only attach the .gpg file which is not publicly readable.

**Comment by Kingom1** [comment]
Do you have Discord?

**Comment by olebeck** [comment]
the bug seems to be fixed now with the changes i just pushed
![image](https://github.com/bedrock-tool/bedrocktool/assets/31539311/546fdfb4-e620-432f-9cba-919d24a69ee0)

**Comment by BJTMastermind** [comment]
Can confirm its fixed. Thanks!
