### ISSUE TITLE
zeqa crash

### ISSUE THREAD

**Issue by FoxGaal** [bedrock-tool/bedrocktool#73]
server crashes on zeqa

**To Reproduce**

select option worlds.
and void generator true 
everything else false
server: eu.zeqa.net:10001

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 22H2 (10 Home)
 - Minecraft Version 1.19.81 and 1.18.83

**attach packets.log.gpg (not always necessary)**
I do not know how to use the console version it just closes (I used the GUI version)

**Comment by olebeck** [comment]
problem is it trying to create a very large image to show the full map, this can be fixed by implementing tiling in the map rendering.
in the mean time you can use the cli version since that doesnt render the map in the gui so doesnt have this issue

**Comment by FoxGaal** [comment]
how do i use the cli version

**Comment by olebeck** [comment]
this should now no longer crash, tiling world map is implemented
