### ISSUE TITLE
cannot register the same state twice

### ISSUE THREAD

**Issue by YopTopwEr** [bedrock-tool/bedrocktool#74]
time="2023-06-06T01:00:45+03:00" level=debug msg="Connected to server."
time="2023-06-06T01:00:47+03:00" level=info msg="Using Custom Blocks"
panic: cannot register the same state twice ({blockState:{Name:custom_heads:custom_winrar_block Properties:map[heads:rotation:1 heads:wall:0] Version:0}})

goroutine 43 [running]:
github.com/df-mc/dragonfly/server/world.registerBlockStates({0xc001682000, 0x6b5, 0x101?})
        /home/runner/go/pkg/mod/github.com/olebeck/dragonfly@v0.9.5-1/server/world/block_state.go:107 +0x174c
github.com/df-mc/dragonfly/server/world.InsertCustomBlocks({0xc00052ea00?, 0x35, 0xc000dc78d0?})
        /home/runner/go/pkg/mod/github.com/olebeck/dragonfly@v0.9.5-1/server/world/block_state.go:225 +0x18c
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*worldsHandler).OnConnect(0xc001722000, {0x0, 0x0?})
        /home/runner/work/bedrocktool/bedrocktool/handlers/worlds/world.go:600 +0x887
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run(0xc001714930, {0x17dc098?, 0xc0022c7e50}, {0xc0005f8618, 0x12}, {0xc0005f8618, 0xc})
        /home/runner/work/bedrocktool/bedrocktool/utils/proxy.go:487 +0xc1d
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldCMD).Execute(0xc000244150, {0x17dc098, 0xc0022c7e50}, {0x17dc648?, 0xc0002b9550?})
        /home/runner/work/bedrocktool/bedrocktool/subcommands/world/world.go:58 +0x1d1
github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute.func1()
        /home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/page.go:160 +0x7d
created by github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute
        /home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/page.go:157 +0xaa

This is not a critical error. But the program still crashes for some reason. It's very easy to fix, my friend even you fixed it.

**Comment by olebeck** [comment]
blockstate system replaced completely, so not sure if still an issue. reopen if so
