### ISSUE TITLE
cannot download skin as a skinpack (error)

### ISSUE THREAD

**Issue by Volonid** [bedrock-tool/bedrocktool#75]
**Describe the bug**
If I try to steal my marketplace skin, it will give me the error time="2023-06-08T22:02:51-07:00" level=warning msg="failed to decode geometry Volonid"

This may be because its a slim skin, but I can't tell

**To Reproduce**
(not sure if it is reproducable since its a specific skin)
1. Do the process of skin stealing
2. Use a slim skin
3. 

**Expected behavior**
For my skin to be downloaded as a skinpack

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 19045.2965
 - Minecraft Version 1.20.0
![Uploading image_2023-06-08_221743545.png…]()

**Comment by olebeck** [comment]
like the log says its just a warning and should still work fine
