### ISSUE TITLE
World Download. Wrong Blocks On CubeCraft

### ISSUE THREAD

**Issue by FreezeEngine** [bedrock-tool/bedrocktool#76]
**Describe the bug**
When I tried to download CubeCraft map, the map looked purple and after a save world contained wrong blocks

1. connect to mco.cubecraft.net through bedrocktool
2. Download the world

**Expected behavior**
For the world to be a 1 to 1 replica

**Screenshots**
![image](https://github.com/bedrock-tool/bedrocktool/assets/19225467/0a97436b-d523-4528-b079-a44ee3b23b2a)

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - Version 22H2
 - Minecraft Version 1.19.83

**Comment by Kingom1** [comment]
Hi

**Comment by olebeck** [comment]
fixed

**Comment by olebeck** [comment]
there are still issues with water on the hub

**Comment by olebeck** [comment]
no longer an issue
