### ISSUE TITLE
World was saved incorrectly

### ISSUE THREAD

**Issue by ytiK0** [bedrock-tool/bedrocktool#81]
I have connected to proxy correctly and successful.  But the map didn't show anything, just filled with purple.
![XOZKv6u9wV](https://github.com/bedrock-tool/bedrocktool/assets/69840482/8506b80f-9b75-4b83-80a5-4f4e6ed89bd0)
After I left the proxy and tried to import the world, it worked. But the world was ruined. in general, there was nothing there
![NVIDIA_Share_eoet1hjEKu](https://github.com/bedrock-tool/bedrocktool/assets/69840482/e69d73af-cafa-4927-9b7a-939c69761f1f)
Minecraft version: 1.20.0.1

**Comment by olebeck** [comment]
should now be fixed
