### ISSUE TITLE
Everything is glitched when i download a map

### ISSUE THREAD

**Issue by Coliade** [bedrock-tool/bedrocktool#82]
I downloaded the hub from this server : mcpe.plutonium.best 19132

using this settings : 
with packs : yes
void Generator : yes
save image : yes
packet capture : yes
I tried without these settings but there is always the glitch
![Minecraft 29_06_2023 15_56_16](https://github.com/bedrock-tool/bedrocktool/assets/106426978/56530c33-c2eb-4434-b25b-a4bc84a30e85)

every blocks are glitched and the air is filled with strange blocks and signs

**Comment by Coliade** [comment]
when im using a map scanner tool like 'unmined' ,the tool just crash

**Comment by olebeck** [comment]
do the logs say "using custom blocks"?

**Comment by Coliade** [comment]
level=info msg="Using Custom Blocks", yes

**Comment by olebeck** [comment]
this should now work
