### ISSUE TITLE
Update 1.20.10?

### ISSUE THREAD

**Issue by Kingom1** [bedrock-tool/bedrocktool#84]
**Describe the bug**
A clear and concise description of what the bug is,
and what server it occurs on.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Version [e.g. 1.28.0-36]
 - Minecraft Version [e.g. 1.19.73]

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS12]
 - Version [e.g. 1.28.0-36]

**Additional context**

**attach packets.log.gpg (not always necessary)**
this file can be helpful for debugging without having to connect to the server.
it can be created by running with -extra-debug [e.g. bedrocktool.exe -extra-debug worlds -address play.mojang.com ]
be sure to only attach the .gpg file which is not publicly readable.

**Comment by UnknxwnGaming** [comment]
![image](https://github.com/bedrock-tool/bedrocktool/assets/63874393/454b229d-1323-465e-9194-a89f7c35fcfa)

Open BedrockTool GUI (1.30.0.0-9)
Click on resources, enter "51.222.46.7" and click start
It will fail to connect and tell you the game needs to be updated

OS: Windows
Version: 1.30.0.0-9
Minecraft Version: 1.20.10.1

**Comment by olebeck** [comment]
released an update if theres any regressions please tell
