### ISSUE TITLE
can't download packs

### ISSUE THREAD

**Issue by 1111qqjzja** [bedrock-tool/bedrocktool#85]
**Describe the bug**
level=error msg="POST https://login.live.com/oauth20_token.srf: refresh error: invalid_grant"

**To Reproduce**
1. Go to 'packs'
2. Click on 'play.cubecraft.net'
3. Scroll down to ''

**Screenshots**
![2PS {8NYW1E 1USJ8$80QRE](https://github.com/bedrock-tool/bedrocktool/assets/89286242/4d9f2468-999e-483d-840a-1e31429f68dc)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Version 1.31.0-0
 - Minecraft Version [e.g. 1.20.12]

**attach packets.log.gpg (not always necessary)**
[e.g. bedrocktool.exe -extra-debug packs -address play.cubecraft.net ]

**Comment by BJTMastermind** [comment]
`play.cubecraft.net` is the Java Edition Server IP, try using `mco.cubecraft.net` which is the IP for the Bedrock Server. 

You can find the list of Featured Servers IPs on the [Minecraft Wiki](https://minecraft.fandom.com/wiki/Featured_servers#List_of_Featured_Servers)

**Comment by 1111qqjzja** [comment]
![{B$X%Z}G9`BK2R5D$P$3H%Q](https://github.com/bedrock-tool/bedrocktool/assets/89286242/eec4b542-d736-491f-99c7-6f54f071bf36)
{
    "error": "invalid_client",
    "error_description": "The provided request must include a 'client_id' input parameter.",
    "correlation_id": "e4b480d3-0595-48f4-bcc4-8b9e0f78db76"
}

**Comment by BJTMastermind** [comment]
I don't make this tool just another user of it. Only other thing i can think of is your missing the token.json file which is created when you sign in to your Microsoft account, as it works fine for me when running the same command.

**Comment by olebeck** [comment]
this error is account specific, you will get the same error logging into xbox.com
