### ISSUE TITLE
failed to connect to : dial raknet: dial udp: missing 

### ISSUE THREAD

**Issue by TOWUK** [bedrock-tool/bedrocktool#87]
time="2023-08-11T20:36:11+03:00" level=info msg="Bedrocktool Version 1.31.0-4"
time="2023-08-11T20:36:30+03:00" level=info msg="Listening on [::]:19132"
time="2023-08-11T20:36:30+03:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2023-08-11T20:36:35+03:00" level=info msg="Connecting to "
time="2023-08-11T20:36:38+03:00" level=error msg="failed to connect to : dial raknet: dial udp: missing address"

IP HIVE BEDROCK
fr.hivebedrock.network
(178.32.53.158)

![image](https://github.com/bedrock-tool/bedrocktool/assets/28830162/40bd1c3e-52f0-4298-82b5-4447502ea55e)

**Comment by TOWUK** [comment]
all last game and tool

**Comment by TOWUK** [comment]
WITHOUT GUI dont work

time="2023-08-11T20:39:19+03:00" level=info msg="Bedrocktool Version 1.31.0-4"
Available Commands:
        chat-log        logs chat to a file
        debug-proxy     verbose debug packets
        realm-address   gets realms address
        list-realms     prints all realms you have access to
        update  self updates to latest version
        trans
        create-customdata
        capture capture packets in a pcap file
        packs   download resource packs from a server
        skins   download skins from players on a server
        worlds  download a world from a server
        blind-proxy     raknet proxy
Use 'bedrocktool <command>' to run a command
Input Command: worlds  ✅
time="2023-08-11T20:39:21+03:00" level=error msg="Fatal Error occurred."

--COPY FROM HERE--
time="2023-08-11T20:39:21+03:00" level=info msg="Version: 1.31.0-4"
time="2023-08-11T20:39:21+03:00" level=info msg="Cmdline: [C:\\Users\\towuk\\Downloads\\bedrocktool-windows-amd64-1.31.0-4.exe worlds]"
time="2023-08-11T20:39:21+03:00" level=error msg="Error: runtime error: index out of range [0] with length 0"
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.main.func1()
        github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:68 +0x1c5
panic({0xfe0e20, 0xc0008b1818})
        runtime/panic.go:884 +0x213
github.com/bedrock-tool/bedrocktool/utils/commands.(*cmdWrap).Execute(0xc000b3aa80?, {0x119a258?, 0xc00008a910?}, 0xc00007a800?, {0x0?, 0x0?, 0xc000515c80?})
        github.com/bedrock-tool/bedrocktool/utils/commands/register.go:32 +0xde
github.com/google/subcommands.(*Commander).Execute(0xc00063e880, {0x119a258, 0xc00008a910}, {0x0, 0x0, 0x0})
        github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x3a2
github.com/google/subcommands.Execute(...)
        github.com/google/subcommands@v1.2.0/subcommands.go:492
github.com/bedrock-tool/bedrocktool/ui/tui.(*TUI).Start(0xc0008cbaa0?, {0x119a258, 0xc00008a910}, 0xc00027aed0)
        github.com/bedrock-tool/bedrocktool/ui/tui/tui.go:55 +0x3d7
main.main()
        github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:123 +0x973

--END COPY HERE--

if you want to report this error, please open an issue at
https://github.com/bedrock-tool/bedrocktool/issues
And attach the error info, describe what you did to get this error.
Thanks!

**Comment by olebeck** [comment]
hopefully fixed this issue with the latest commit, if you still have it please open this issue again
