### ISSUE TITLE
parse login request: validate token 2: square/go-jose/jwt: validation field, token issued in the future (iat)

### ISSUE THREAD

**Issue by CleoWay** [bedrock-tool/bedrocktool#88]
2023/08/11 21:05:41 error: parse login request: validate token 2: square/go-jose/jwt: validation field, token issued in the future (iat)

![image](https://github.com/bedrock-tool/bedrocktool/assets/50581592/2daea1bd-6c31-411b-a69e-f83dc256e5bb)

**Comment by olebeck** [comment]
your pc time is likely set wrong
