### ISSUE TITLE
realm-address command error

### ISSUE THREAD

**Issue by 1111qqjzja** [bedrock-tool/bedrocktool#93]
the log : Use 'bedrocktool <command>' to run a command
Input Command: time="2023-08-18T18:54:21+08:00" level=info msg="Update available: 1.31.0-30  use the update command to install it."
Input Command: realm-address  ✅
time="2023-08-18T18:54:28+08:00" level=error msg="Fatal Error occurred."

--COPY FROM HERE--
time="2023-08-18T18:54:28+08:00" level=info msg="Version: 1.31.0-0"
time="2023-08-18T18:54:28+08:00" level=info msg="Cmdline: [C:\\Users\\王泽利\\Documents\\Tencent Files\\918341818\\FileRecv\\MobileFile\\bedrocktool-windows-amd64-1.31.0-0.exe realm-address]"
time="2023-08-18T18:54:28+08:00" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.main.func1()
        github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:87 +0x1c5
panic({0x12191a0, 0x1c09de0})
        runtime/panic.go:884 +0x213
github.com/sandertv/gophertunnel/minecraft/realms.(*Client).XboxToken(0xc000c1e6c0, {0x14692f8, 0xc00043df90})
        github.com/sandertv/gophertunnel@v1.30.0/minecraft/realms/realms.go:172 +0x42
github.com/sandertv/gophertunnel/minecraft/realms.(*Client).RequestWithMethod(0xc000c1e6c0, {0x14692f8, 0xc00043df90}, {0x1315689, 0x7}, {0x13128eb, 0x3}, {0x0, 0x0}, {0x0, ...})
        github.com/sandertv/gophertunnel@v1.30.0/minecraft/realms/realms.go:203 +0x4a7
github.com/sandertv/gophertunnel/minecraft/realms.(*Client).Request(...)
        github.com/sandertv/gophertunnel@v1.30.0/minecraft/realms/realms.go:183
github.com/sandertv/gophertunnel/minecraft/realms.(*Client).Realms(0xc000c1e6c0, {0x14692f8?, 0xc00043df90?})
        github.com/sandertv/gophertunnel@v1.30.0/minecraft/realms/realms.go:251 +0x59
github.com/bedrock-tool/bedrocktool/utils.getRealm({0x14692f8, 0xc00043df90}, {0x13151ff, 0x0}, {0x0, 0x0})
        github.com/bedrock-tool/bedrocktool/utils/realms.go:10 +0x73
github.com/bedrock-tool/bedrocktool/utils.ServerInput({0x14692f8, 0xc00043df90}, {0x13151ff?, 0x0?})
        github.com/bedrock-tool/bedrocktool/utils/input.go:133 +0x16e
github.com/bedrock-tool/bedrocktool/subcommands.(*RealmAddressCMD).Execute(0x5?, {0x14692f8, 0xc00043df90}, {0xb2a64f?, 0x10fd1e2?})
        github.com/bedrock-tool/bedrocktool/subcommands/realm-address.go:22 +0x51
github.com/bedrock-tool/bedrocktool/utils.(*cmdWrap).Execute(0xc0009e4840?, {0x14692f8?, 0xc00043df90?}, 0xc000076800?, {0xc00061faa0?, 0x0?, 0xc000111c80?})
        github.com/bedrock-tool/bedrocktool/utils/command_register.go:31 +0x3e
github.com/google/subcommands.(*Commander).Execute(0xc000c80e80, {0x14692f8, 0xc00043df90}, {0x0, 0x0, 0x0})
        github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x3a2
github.com/google/subcommands.Execute(...)
        github.com/google/subcommands@v1.2.0/subcommands.go:492
github.com/bedrock-tool/bedrocktool/utils.(*InteractiveCLI).Start(0xc00063a360?, {0x14692f8, 0xc00043df90}, 0xc000533430)
        github.com/bedrock-tool/bedrocktool/utils/iui.go:82 +0x3d7
main.main()
        github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:162 +0x945
console :
![image](https://github.com/bedrock-tool/bedrocktool/assets/89286242/228cca19-4d8b-49b4-af09-c9ce49ae8e22)

**Comment by olebeck** [comment]
should be fixed now
