### ISSUE TITLE
Pack downloader and world downloader dont work

### ISSUE THREAD

**Issue by tim03we** [bedrock-tool/bedrocktool#94]
**Describe the bug**
I specify the IP or the domain and after it tries to connect, it closes everything directly and it doesn't download anything. In the same way you can not download the world. The does not connect to the server

**To Reproduce**

**Expected behavior**
Downloads the pack

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Minecraft Version 1.20.12

**Additional context**

**attach packets.log.gpg (not always necessary)**
this file can be helpful for debugging without having to connect to the server.
it can be created by running with -extra-debug [e.g. bedrocktool.exe -extra-debug worlds -address play.mojang.com ]
be sure to only attach the .gpg file which is not publicly readable.

**Comment by olebeck** [comment]
you didnt specify any reproduction steps and i cant replicate this error on servers i test on, please the add server address and how you are running the program
