### ISSUE TITLE
Cant Use

### ISSUE THREAD

**Issue by DranxX** [bedrock-tool/bedrocktool#96]
If me grabb world error:  parse login request: identity data must have an XUID when logged into XBOX Live only

If me grabb packs error: time="2023-08-23T22:18:00+07:00" level=info msg="Version: 1.31.0-47"
time="2023-08-23T22:18:00+07:00" level=info msg="Cmdline: [D:\\IDM\\Programs\\bedrocktool-windows-amd64-1.31.0-47.exe packs]"
time="2023-08-23T22:18:00+07:00" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.main.func1()
        github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:82 +0x1d2
panic({0xdaf500, 0x17adf20})
        runtime/panic.go:884 +0x213
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).doSession(0xc000e74700, {0xff69d8?, 0xc000e3ac80}, 0xc000e14e50)
        github.com/bedrock-tool/bedrocktool/utils/proxy/context.go:364 +0x831
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).connect(0xc000e74700, {0xff69d8, 0xc000d4c280})
        github.com/bedrock-tool/bedrocktool/utils/proxy/context.go:459 +0x146
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).Run(0xc000e74700, {0xff69d8, 0xc000d4c280}, {0xc000e0c408?, 0xd55140?}, {0xc000e0c408?, 0xc000e168f0?})
        github.com/bedrock-tool/bedrocktool/utils/proxy/context.go:508 +0x558
github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d.Execute_cmd({0xff69d8, 0xc000d4c280}, {0x0?, 0xc00008bb98?}, 0x0, 0x0, {0xff6ea8?, 0x1814a30}, 0xc000e39e00?)
        github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d/resourcepack-d.go:391 +0x3f2
github.com/bedrock-tool/bedrocktool/subcommands.(*ResourcePackCMD).Execute(0xeb4ed7?, {0xff69d8?, 0xc000d4c280?}, {0xff6ea8?, 0x1814a30?})
        github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d.go:33 +0x57
github.com/bedrock-tool/bedrocktool/utils/commands.(*cmdWrap).Execute(0xc000ce5060, {0xff69d8, 0xc000d4c280}, 0x10?, {0xc000e14a60?, 0xd73ec0?, 0xc00008bc88?})
        github.com/bedrock-tool/bedrocktool/utils/commands/register.go:35 +0x82
github.com/google/subcommands.(*Commander).Execute(0xc000ce2b00, {0xff69d8, 0xc000d4c280}, {0xc000e14a60, 0x1, 0x1})
        github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x3a2
github.com/google/subcommands.Execute(...)
        github.com/google/subcommands@v1.2.0/subcommands.go:492
github.com/bedrock-tool/bedrocktool/ui/tui.(*TUI).Start(0x1814a30, {0xff69d8, 0xc000d4c280}, 0xc000d22e50)
        github.com/bedrock-tool/bedrocktool/ui/tui/tui.go:56 +0x425
main.main()
        github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:136 +0x8b3

**Comment by olebeck** [comment]
both of these should now be fixed, mojang changed their private key so i had to update it
