### ISSUE TITLE
World downloader broken

### ISSUE THREAD

**Issue by u4gy** [bedrock-tool/bedrocktool#97]
level=error msg="Get \"https://updates.yuv.pink/bedrocktool/windows-amd64.json\": dial tcp: lookup updates.yuv.pink: i/o timeout"

![image](https://github.com/bedrock-tool/bedrocktool/assets/113064988/9632ef6e-f900-45a6-ac8a-70f811e17db5)

When I try to join it kicks me off

![image](https://github.com/bedrock-tool/bedrocktool/assets/113064988/0da86818-8354-4b87-bc49-9c5976b21214)

**Comment by u4gy** [comment]
Also when I look up the links nothing comes up 

![image](https://github.com/bedrock-tool/bedrocktool/assets/113064988/1e86bfda-b9d1-4cae-908b-f5a789495cf2)

**Comment by olebeck** [comment]
the error that was being shown in the console is unrelated, you need to press the select command button and enter a server address, then press start before you try to join in the game

**Comment by u4gy** [comment]
![image](https://github.com/bedrock-tool/bedrocktool/assets/113064988/a919f2c4-349a-47ab-b6ce-6d09473168fe)

where is start

**Comment by u4gy** [comment]
![image](https://github.com/bedrock-tool/bedrocktool/assets/113064988/a6b0958a-3463-45f8-b897-b3d5305a0f40)

i get this error

**Comment by olebeck** [comment]
do you use some kind of proxy or antivirus preventing https from working

**Comment by u4gy** [comment]
I switched my antivuirus of and got this error
